
####################################################################################################
########## Top Cards
####################################################################################################
[[favorite]]
name = "Brother's Gift"
reward = "5x div"
drop_level = 68
info = "Cemetery Map • Grave Trough Map • Graveyard Map"

[[favorite]]
name = "House of Mirrors"
reward = "1x Mirror of Kalandra"
drop_level = 78
info = "The Alluring Abyss (uber atziri)"

[[favorite]]
name = "I See Brothers"
reward = "2x fracturing orb"
drop_level = 68
info = "various map bosses"

[[favorite]]
name = "Seven Years Bad Luck"
reward = "1x Mirror shard"
drop_level = 35
info = "Crimson Temple Map • Defiled Cathedral Map"

[[favorite]]
name = "The Immortal"
reward = "House of Mirrors Card"
drop_level = 35
info = "The Hall of Grandmasters"

[[favorite]]
name = "Unrequited Love"
reward = "19x Mirror Shard"
drop_level = 35
info = "The Temple of Decay Level 1 • Maze Map • Vaal Pyramid Map • Vaults of Atziri • Vaal Temple Map"

####################################################################################################
########## Favorite Cards
####################################################################################################
[[good]]
name = "Brother's Stash"
reward = "5x exalted"
drop_level = 68
info = "Cemetery Map • Grave Trough Map • Graveyard Map"

[[good]]
name = "Darker Half"
reward = "5x eldricht Exalted"
drop_level = 81
info = "Drops when receiving Currency rewards from Delirium layers in maps (from Delirium Mirror or Delirium Orbs) and in Simulacrum."

[[favorite]]
name = "Divine Beauty"
reward = "7x div"
drop_level = 68
info = "Drops from Merveil in both Underground Sea Map and Maelström of Chaos"

[[favorite]]
name = "Harmony of Souls"
reward = "9x shrieking essence"
drop_level = 68
info = "Abomination Map Can drop from versions of Doedre, Maligaro, and Shavronne in Sepulchre Map, Overgrown Shrine Map, and Cells Map respectively, as well as Abomination Map"

[[favorite]]
name = "The Cacophony"
reward = "3x defening essence"
drop_level = 68
info = "Drops from Merveil, the Returned in both Underground Sea Map and Maelström of Chaos"

[[good]]
name = "The Long Con"
reward = "Elderslayer's Exalted Orb"
drop_level = 80
info = "This card drops from Izaro's Treasure chests in the Eternal Labyrinth (Uber Lab) and Enriched Eternal Labyrinth."

[[favorite]]
name = "The Sephirot"
reward = "10x div"
drop_level = 35
info = "Dominus, Ascendant Excellis Aurafix The Hallowed Husk The Hallowed Husk The High Templar"


####################################################################################################
########## Useful Cards
####################################################################################################
[[good]]
name = "Abandoned Wealth"
reward = "3x exalted"
drop_level = 68
info = "Mao Kun map"

[[good]]
name = "Alluring Bounty"
reward = "10x exalted"
drop_level = 68
info = "The Apex of Sacrifice • The Alluring Abyss"

[[hide]]
name = "Ambitious Obsession"
reward = "Skittering Delirium Orb"
drop_level = 68
info = "Ara Sister of Light, Armala, the Widow, Drek Apex Hunter, Erebix Light's Bane, Gorulis Will-Thief, Khor Sister of Shadows, Mephod the Earth Scorcher, Nassar Lion of the Seas, Stalker of the Endless Dunes, Tahsin Warmaker, Terror of the Infinite Drifts, Varhesh Shimmering Aberration"

[[good]]
name = "Chaotic Disposition"
reward = "5x Chaos Orb"
drop_level = 23
info = "Poorjoy's Asylum"

[[good]]
name = "Coveted Possession"
reward = "5x Regal Orb"
drop_level = 23
info = "The Catacombs • The Ossuary (Act 5) • The Ossuary (Act 10) • Bone Crypt Map • Sanctuary Map • Ziggurat Map"

[[favorite]]
name = "Dementophobia"
reward = "10x Delerium Orb"
drop_level = 68
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer, Venarius"

[[favorite]]
name = "Demigod's Wager"
reward = "Orb of Annulment"
drop_level = 35
info = "The Cleansing Light"

[[hide]]
name = "Disdain"
reward = "Delerium Orb"
drop_level = 44
info = "Can drop after completing any Maven's Invitation, including Quest ones."

[[good]]
name = "Ever-Changing"
reward = "10x Orb of Unmaking"
drop_level = 68
info = "Drops in maps opened via Kirac missions."

[[good]]
name = "Lucky Connections"
reward = "20x Orb of Fusing"
drop_level = 23
info = "The Docks • The Quay • Pier Map • Port Map • Shipyard Map • Wharf Map"

[[good]]
name = "The Cartographer"
reward = "10x cartographers chisel"
drop_level = 39
info = "Drops from Cartographer's Strongboxes."

[[good]]
name = "The Fortunate"
reward = "2x div"
drop_level = 68
info = "Ancient City Map • Arid Lake Map • Atoll Map • Beach Map • Burial Chambers Map • Caldera Map • Canyon Map • Desert Map • Desert Spring Map • Dry Sea Map • Dunes Map • Estuary Map • Fields Map • Jungle Valley Map • Leyline Map • Marshes Map • Mesa Map • Mineral Pools Map • Orchard Map • Peninsula Map • Plateau Map • Shore Map • Sulphur Vents Map • Terrace Map • Crater Map • Tropical Island Map"

[[good]]
name = "The Heroic Shot"
reward = "17x chromatic"
drop_level = 23
info = "Can drop from Arcanist's Strongboxes"

[[good]]
name = "The Hoarder"
reward = "Exalted Orb"
drop_level = 68
info = "Maelström of Chaos • Mineral Pools Map • Underground Sea Map • Vaults of Atziri • Vault Map"

[[good]]
name = "The Innocent"
reward = "40x Orb of Regret"
drop_level = 23
info = "The Chamber of Innocence • Basilica Map • Defiled Cathedral Map • Sanctuary Map"

[[favorite]]
name = "The Rusted Bard"
reward = "4x Tainted Mythic Orb"
drop_level = 68
info = "The Vinktar Square"

[[good]]
name = "The Saint's Treasure"
reward = "2x Exalted Orb"
drop_level = 68
info = "Alleyways Map • Arcade Map • Bazaar Map • Ghetto Map • Port Map • Precinct Map"

[[good]]
name = "The Scout"
reward = "7x Exalted Orb"
drop_level = 68
info = "Ashen Wood Map • Bramble Valley Map • Dark Forest Map • Forbidden Woods Map • Jungle Valley Map • Lair Map • Ramparts Map • Spider Forest Map • Stagnation Map • Thicket Map • Tropical Island Map"

[[favorite]]
name = "The Seeker"
reward = "3x Orb of Annulment"
drop_level = 35
info = "The Temple of Atzoatl"

[[favorite]]
name = "The Side Quest"
reward = "20x Scouting Report"
drop_level = 69
info = "Alleyways Map • Arachnid Tomb Map • Armoury Map • Castle Ruins Map • Forking River Map • Iceberg Map • Infested Valley Map • Mineral Pools Map • Siege Map • Primordial Blocks Map"

[[good]]
name = "The Transformation"
reward = "Tainted Mythic Orb"
drop_level = 68
info = "Drops from bosses with the 'transform_boss' monster tag."

[[good]]
name = "The Wrath"
reward = "10x Chaos Orb"
drop_level = 23
info = "The Cathedral Rooftop (Act 5) • The Feeding Trough • Belfry Map • Lava Lake Map"

[[good]]
name = "Three Faces in the Dark"
reward = "3x Chaos Orb"
drop_level = 23
info = "The Grain Gate • The Refinery • Arsenal Map • Factory Map • Port Map"

[[hide]]
name = "Vinia's Token"
reward = "10x orb of regret"
drop_level = 68
info = "Core Map • Malformation Map • Shrine Map"

####################################################################################################
########## Silly Gamble Cards
####################################################################################################
[[good]]
name = "Emperor's Luck"
reward = "5x currency"
drop_level = 23
info = "The Imperial Gardens • The High Gardens • Courtyard Map • Gardens Map • Orchard Map • Terrace Map"

[[good]]
name = "Lucky Deck"
reward = "10x stacked deck"
drop_level = 74
info = "Ziggurat Map"

[[good]]
name = "Parasitic Passengers"
reward = "10x Incubator"
drop_level = 68
info = "Arachnid Tomb Map • Channel Map • Infested Valley Map"

[[good]]
name = "The Tireless Extractor"
reward = "10x oil"
drop_level = 68
info = "Factory Map • Fortress Map • Port Map • Silo Map"

[[good]]
name = "Three Voices"
reward = "3x Essence"
drop_level = 23
info = "Arena Map • City Square Map • Courthouse Map • Courtyard Map • Crystal Ore Map • Forbidden Woods Map • Graveyard Map • Racecourse Map • Vaal Pyramid Map • Vaal Temple Map"


####################################################################################################
########## Hidden Cards
####################################################################################################

[[good]]
name = "A Sea of Blue"
reward = "13x Orb of Alteration"
drop_level = 68
info = "Citadel Map • Crystal Ore Map • Grotto Map • Mineral Pools Map • Primordial Blocks Map • Ziggurat Map"

[[good]]
name = "Acclimatisation"
reward = "20x Orb of Alteration"
drop_level = 23
info = "Desert Map • Desert Spring Map • Dry Sea Map • Dunes Map"

[[hide]]
name = "Loyalty"
reward = "3x fusing"
drop_level = 0
info = "TODO"

[[good]]
name = "No Traces"
reward = "10x Orb of Scouring"
drop_level = 23
info = "The Ossuary (Act 5) • The Reliquary (Act 10) • The Ossuary (Act 10) • Mausoleum Map • Relic Chambers Map • Sepulchre Map • Ziggurat Map"

[[hide]]
name = "Rain of Chaos"
reward = "1x chaos"
drop_level = 0
info = "TODO"

[[hide]]
name = "Society's Remorse"
reward = "10x alt"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Catalyst"
reward = "1x vaal"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Finishing Touch"
reward = "fertile catalyst (life and mana)"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Fool"
reward = "20x chance"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Gemcutter"
reward = "Gemcutter's Prism"
drop_level = 0
info = "todo"

[[good]]
name = "The Inventor"
reward = "10x Vaal Orb"
drop_level = 23
info = "The Ancient Pyramid • The Temple of Decay Level 1 • The Temple of Decay Level 2 • Maze Map • Doryani's Machinarium • Vaal Pyramid Map • Vaults of Atziri • Vaal Temple Map"

[[hide]]
name = "The Journey"
reward = "harbringers orb"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Master Artisan"
reward = "20x q currency"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Scholar"
reward = "40x wiz"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Survivalist"
reward = "7x alchemy"
drop_level = 0
info = "TODO"

[[good]]
name = "The Tinkerer's Table"
reward = "5x fossil"
drop_level = 23
info = "lots of maps"

[[good]]
name = "The Union"
reward = "10x gemcutters prism"
drop_level = 23
info = "The Fellshrine Ruins (Act 7) • Cemetery Map • Grave Trough Map • Graveyard Map"
