####################################################################################################
########## Minion: Top
####################################################################################################


####################################################################################################
########## Minion: All Season
####################################################################################################
[[all_season]]
name = "Terrible Secret of Space"
reward = "level 21 trans golem gem Corrupted"
drop_level = 72
info = "Avatar of Undoing, Calderus, Fragment of Winter, Guardian of the Vault, Pirate Treasure, Stone of the Currents, Telvar, the Inebriated, The Eroding One, Titan of the Grove, Void Anomaly"

####################################################################################################
########## Minion: Mix
####################################################################################################

####################################################################################################
########## Minion: Gamble
####################################################################################################
[[hide]]
name = "A Stone Perfected"
reward = "Jewel Primordial Corrupted (golem)"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Primordial"
reward = "primordial jewel (golem) (golem)"
drop_level = 0
info = "TODO"

####################################################################################################
########## Minion: Hidden Unless SSF
####################################################################################################
[[hide]]
name = "Dark Dreams"
reward = "Elder influenced Bone Helmet"
drop_level = 80
info = "Minara Anemina"

[[hide]]
name = "Death"
reward = "Mon'tregul's Grasp Void Sceptre"
drop_level = 51
info = "Abomination Map • Bog Map • Marshes Map • Mud Geyser Map"

[[hide]]
name = "The Craving"
reward = "Unending Hunger Cobalt Jewel"
drop_level = 23
info = "Infector of Dreams, Rose, The Bone Sculptor, Thorn, Xixic High Necromancer"

[[hide]]
name = "The Darkest Dream"
reward = "corrupted Severed in Sleep Cutlass"
drop_level = 80
info = "Whakawairua Tuahu"

[[hide]]
name = "The Lich"
reward = "Midnight Bargain Engraved Wand (minion)"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Return of the Rat"
reward = "Tavukai Coral Amulet (minion srs)"
drop_level = 0
info = "TODO"

####################################################################################################
########## Minion: Hidden
####################################################################################################
[[hide]]
name = "Grave Knowledge"
reward = "+20% quality Summon Raging Spirit"
drop_level = 23
info = "The Catacombs • The Ossuary (Act 5) • The Ossuary (Act 10) • The Crypt (Act 7) • Bone Crypt Map • Citadel Map • Cursed Crypt Map • The Coward's Trial • Necropolis Map • Sanctuary Map • Ziggurat Map"

[[hide]]
name = "Keeper's Corruption"
reward = "blue eldricth bone helm - elder but found in breach realm"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Army of Blood"
reward = "Bloodbond chest"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Bones"
reward = "Corrupted Level 21 Vaal Summon Skeletons"
drop_level = 72
info = "Minara Anemina"

[[hide]]
name = "The Forsaken"
reward = "Umbilicus Immortalis Leather Belt (heals zombies shit)"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Rite of Elements"
reward = "lvl 21 golem gem Corrupted (golem)"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Skeleton"
reward = "q23 summon skeleton Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Summoner"
reward = "20% minion gem"
drop_level = 0
info = "TODO"
