
####################################################################################################
########## Decent Cards
####################################################################################################
[[good]]
name = "Anarchy's Price"
reward = "Voltaxic Rift Spine Bow Corrupted"
drop_level = 48
info = "This item can drop from Rogue Exiles."

[[hide]]
name = "The Porcupine"
reward = "ilvl 50 six-link Normal Short Bow"
drop_level = 38
info = "The High Gardens • Courtyard Map • Gardens Map • Orchard Map • Plaza Map • Terrace Map"

[[good]]
name = "Tranquillity"
reward = "Voltaxic Rift Spine Bow"
drop_level = 48
info = "Ashen Wood, Fields, Orchard, Peninsula, The Ashen Fields"


####################################################################################################
########## Useful Cards
####################################################################################################
[[hide]]
name = "A Note in the Wind"
reward = "Asenath's Mark - (manaforged arrow trigger type helmet)"
drop_level = 0
info = "TODO"

[[hide]]
name = "Bowyer's Dream"
reward = "ilvl 91 six-link Normal Harbinger Bow"
drop_level = 0
info = "TODO"

[[hide]]
name = "Imperial Legacy"
reward = "white 6link Imperial Bow"
drop_level = 0
info = "TODO"


####################################################################################################
########## Silly Gamble Cards
####################################################################################################
[[hide]]
name = "Hunter's Resolve"
reward = "random unique bow"
drop_level = 23
info = "The Riverways (Act 6) • The Southern Forest (Act 6) • The Sarn Ramparts • Forking River Map • Ramparts Map"


####################################################################################################
########## Hidden Cards
####################################################################################################

[[hide]]
name = "Endless Night"
reward = "Maloney's Mechanism Ornate Quiver"
drop_level = 0
info = "TODO"

[[hide]]
name = "Etched in Blood"
reward = "rigwalds quills quiver Two-Implicit Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Fletcher"
reward = "drillneck quiver Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Wind"
reward = "Windripper imperial bow"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Wolven King's Bite"
reward = "rigwalds quills quiver"
drop_level = 0
info = "TODO"

[[hide]]
name = "Thunderous Skies"
reward = "Storm Cloud long bow"
drop_level = 0
info = "TODO"

[[hide]]
name = "Vile Power"
reward = "Doomfletch Royal Bow"
drop_level = 0
info = "TODO"
