
####################################################################################################
########## Top Cards
####################################################################################################
[[favorite]]
name = "Beauty Through Death"
reward = "Atziri's Reflection Golden Buckler"
drop_level = 56
info = "K'aj A'alai, K'aj Q'ura, K'aj Y'ara'az (corrupt vaal temple)"

[[favorite]]
name = "Choking Guilt"
reward = "Stranglegasp Onyx Amulet"
drop_level = 80
info = "The Infinite Hunger"

[[favorite]]
name = "Divine Justice"
reward = "Grand Spectrum jewel Corrupted"
drop_level = 56
info = "Armourer's Strongbox"

[[favorite]]
name = "Fire Of Unknown Origin"
reward = "Nimis Topaz Ring"
drop_level = 81
info = "Academy, Residence"

[[favorite]]
name = "Love Through Ice"
reward = "Two-Implicit Corrupted Unnatural Instinct Viridian Jewel - (Allocated Small Passive Skills in Radius grant nothing Grants all bonuses of Unallocated Small Passive Skills in Radius) can be excellent with the parandus pact"
drop_level = 54
info = "Veritania, The Redeemer (conquerer)"

[[favorite]]
name = "Succor of the Sinless"
reward = "Bottled Faith Sulphur Flask"
drop_level = 79
info = "Sanctuary (t17map)"

[[favorite]]
name = "The Apothecary"
reward = "Mageblood Heavy Belt"
drop_level = 75
info = "Crimson Temple Map • Crimson Township Map • Defiled Cathedral Map • Haunted Mansion Map"

[[favorite]]
name = "The Demon"
reward = "Headhunter Leather Belt Two-Implicit Corrupted"
drop_level = 68
info = "Lord of the Grey (Belfry Map), Megaera (Crater Map), The Destroyer's Heart (Lava Lake Map)"

[[favorite]]
name = "The Endless Darkness"
reward = "Voidforge Infernal Sword"
drop_level = 81
info = "The Beachhead, Beachhead (unique harbringer maps), Delve. Harbinger Portals in Kirac's Memory of Phaaryl."

[[favorite]]
name = "The Gulf"
reward = "Thread of Hope crimson Jewel Two-Implicit Corrupted"
drop_level = 86
info = "Uber Elder only (Passives in Radius can be Allocated without being connected to your tree)"

[[favorite]]
name = "The Insane Cat"
reward = "Mageblood Heavy Belt corrupted"
drop_level = 68
info = "Drops from Omniphobia and Kosis in map areas affected by Delirium."

[[favorite]]
name = "The Price of Devotion"
reward = "Mageblood Heavy Belt Quality +20% Two-Implicit Corrupted"
drop_level = 75
info = "Uber Atziri."

[[favorite]]
name = "The Progeny of Lunaris"
reward = "Dying Sun Ruby Flask"
drop_level = 81
info = "Helial, the Day Unending (The Twilight Temple Moon Temple Map), Khor, Sister of Shadows (Cold River Map), Sebbert, Crescent's Point (Moon Temple Map), Selenia, the Endless Night (The Twilight Temple Moon Temple Map)"

####################################################################################################
########## High Value
####################################################################################################

[[good]]
name = "The Doctor"
reward = "Headhunter Leather Belt"
drop_level = 68
info = "Abomination Map • Burial Chambers Map • The Putrid Cloister • Phantasmagoria Map • Sepulchre Map • Spider Forest Map • Waste Pool Map"

[[good]]
name = "The Fiend"
reward = "Headhunter Leather Belt Corrupted"
drop_level = 68
info = "Foundry Map • Laboratory Map • Shrine Map • Poorjoy's Asylum"

[[good]]
name = "The Greatest Intentions"
reward = "The Saviour Legion Sword Two-Implicit Corrupted"
drop_level = 81
info = "Maven's Invitation: The Feared (shaper)"

[[good]]
name = "The Price of Loyalty"
reward = "Skin of the Loyal Simple Robe (Two-Implicit Corrupted)"
drop_level = 79
info = "Zilquapa, Architect of the Breach"

####################################################################################################
########## Useful Cards
####################################################################################################

####################################################################################################
########## Silly Gamble Cards
####################################################################################################


####################################################################################################
########## Hidden Cards
####################################################################################################
