####################################################################################################
########## Content: All Season
####################################################################################################
[[all_season]]
name = "A Fate Worse Than Death"
reward = "Cortex Synthesised Map Corrupted"
drop_level = 78
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer, Sirus Awakener of Worlds"

[[all_season]]
name = "Altered Perception"
reward = "simulacrum (can drop Megalomaniac mcluster, Split Personality Crimson Jewel, Voices (Cluster)"
drop_level = 68
info = "Uhtred Covetous Traitor"

[[all_season]]
name = "Eternal Bonds"
reward = "Replica Cortex Synthesised Map"
drop_level = 78
info = "Drops from Map Reward Chests in Heist Contracts and Blueprints"

[[hide]]
name = "Sambodhi's Vow"
reward = "mortal fragment (uber atziri)"
drop_level = 70
info = "Can drop from members of the Immortal Syndicate."

[[all_season]]
name = "Something Dark"
reward = "83 blueprint fully revealed"
drop_level = 75
info = "Drops from Breachlords in Breachstones."

[[all_season]]
name = "The Eldritch Decay"
reward = "uber elder fragment"
drop_level = 81
info = "The Constrictor The Enslaver The Eradicator The Purifier"

[[all_season]]
name = "The Eye of Terror"
reward = "Chayula's Flawless Breachstone"
drop_level = 68
info = "It That Fled"

####################################################################################################
########## Content: Mix
####################################################################################################
[[good]]
name = "Checkmate"
reward = "76x simulacrum splinter"
drop_level = 68
info = "Academy Map • Museum Map • Scriptorium Map"

[[good]]
name = "Guardian's Challenge"
reward = "Shaper Guardian Map"
drop_level = 81
info = "Sold by Kirac for 3x Cartographer's Chisel"

[[good]]
name = "Last Hope"
reward = "Mortal Hope (opens vaal areas and buffs map quality)"
drop_level = 68
info = "Atziri, Queen of the Vaal"

[[good]]
name = "Lingering Remnants"
reward = "vaal temple map Corrupted"
drop_level = 78
info = "Drops in a lot of maps"

[[good]]
name = "The Obscured"
reward = "Breachstone"
drop_level = 68
info = "The Obscured can drop from Abyss monsters, including from Abyss nodes in Delve."

[[good]]
name = "The Price of Prescience"
reward = "Vaal Temple Map T16 Delirium: 100% Corrupted"
drop_level = 78
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer"

[[good]]
name = "The Price of Protection"
reward = "Elder Guardian Occupied Map T: 14 to 16 Modifiers: 8 Corrupted"
drop_level = 81
info = "Drops from Invasion bosses or Vaal side area bosses."

####################################################################################################
########## Content: Hideable Unique maps
####################################################################################################
[[good]]
name = "Justified Ambition"
reward = "Synthesis Map"
drop_level = 81
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer"

[[good]]
name = "Scholar of the Seas"
reward = "Mao Kun Unique map"
drop_level = 68
info = "The Brine King's Reef • Coves Map • Reef Map • Strand Map • Whakawairua Tuahu"

[[good]]
name = "The Dreamland"
reward = "Poorjoy's Asylum Unique map"
drop_level = 68
info = "Drops from Cartographer's Strongboxes."

[[good]]
name = "The Landing"
reward = "The Breachhead Unique map"
drop_level = 73
info = "Shore Map • Mao Kun • Strand Map • Whakawairua Tuahu"

[[good]]
name = "The Professor"
reward = "The Putrid Cloister Unique Museum Map"
drop_level = 68
info = "Academy Map • Laboratory Map • Museum Map • Scriptorium Map"

[[good]]
name = "The Twilight Moon"
reward = "The Twilight Temple Map"
drop_level = 68
info = "Cold River Map • Moon Temple Map • Temple Map"

[[good]]
name = "The Wolf's Legacy"
reward = "Vaults of Atziri Unique map"
drop_level = 68
info = "This card drops from Izaro's Treasure chests, Labyrinth Troves, or Silver Key caches in the Eternal Labyrinth or Enriched Eternal Labyrinth. Still requires verification if it can drop in Merciless Labyrinth."

[[good]]
name = "Treasure Hunter"
reward = "Vaults of Atziri Unique map"
drop_level = 68
info = "Museum Map • Relic Chambers Map • Vaults of Atziri • Vault Map"

####################################################################################################
########## Content: Gamble
####################################################################################################
[[gamble]]
name = "Buried Treasure"
reward = "sulphite scarab"
drop_level = 0
info = "TODO"

[[gamble]]
name = "Cameria's Cut"
reward = "Scarab"
drop_level = 68
info = "Cameria the Coldblooded"

[[gamble]]
name = "Man With Bear"
reward = "bestiary scarab"
drop_level = 68
info = "Barrows Map • Cemetery Map"

[[gamble]]
name = "The Card Sharp"
reward = "divination scarab"
drop_level = 68
info = "alva missions + Alva's Memory of Reverse Incursion."

[[gamble]]
name = "The Deal"
reward = "cartography scarab"
drop_level = 68
info = "Cameria the Coldblooded"

[[good]]
name = "The Encroaching Darkness"
reward = "Map Corrupted"
drop_level = 73
info = "lotta maps"

####################################################################################################
########## Content: Hidden Unless SSF
####################################################################################################
[[hide]]
name = "Azure Rage"
reward = "Random Punishing Magic tier 16 map (phsyical reflect)"
drop_level = 81
info = "Factory Map • Port Map"

[[hide]]
name = "Left to Fate"
reward = "Random unidentified corrupted tier 16 Rare map"
drop_level = 73
info = "Forking River Map • Ramparts Map"

[[hide]]
name = "The Puzzle"
reward = "5x breech stone splinter"
drop_level = 68
info = "The Puzzle can drop from Beyond demons."

####################################################################################################
########## Content: Hidden
####################################################################################################
[[hide]]
name = "Boon of Justice"
reward = "Offering to the Goddess"
drop_level = 73
info = "Chateau Map • Conservatory Map • Orchard Map • Plaza Map"

[[hide]]
name = "Cartographer's Delight"
reward = "tier 5 map"
drop_level = 0
info = "TODO"

[[hide]]
name = "Her Mask"
reward = "saccrifice fragment"
drop_level = 0
info = "TODO"

[[hide]]
name = "Rain Tempter"
reward = "tier 6 map"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Arena Champion"
reward = "tier 12 map"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Surveyor"
reward = "tier 14 map"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Trial"
reward = "tier 15 map Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "Triskaidekaphobia"
reward = "corrup tier 13 map 8 modifiers"
drop_level = 0
info = "TODO"
