
[[hide]]
name = "A Stone Perfected"
reward = "Jewel Primordial Corrupted (golem) ##### MINION"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Primordial"
reward = "primordial jewel (golem) (golem)"
drop_level = 0
info = "TODO"







[[hide]]
name = "Dark Dreams"
reward = "Elder influenced Bone Helmet"
drop_level = 80
info = "Minara Anemina"

[[hide]]
name = "Death"
reward = "Mon'tregul's Grasp Void Sceptre"
drop_level = 51
info = "Abomination Map • Bog Map • Marshes Map • Mud Geyser Map"

[[hide]]
name = "The Craving"
reward = "Unending Hunger Cobalt Jewel"
drop_level = 23
info = "Infector of Dreams, Rose, The Bone Sculptor, Thorn, Xixic High Necromancer"

[[hide]]
name = "The Darkest Dream"
reward = "corrupted Severed in Sleep Cutlass"
drop_level = 80
info = "Whakawairua Tuahu"

[[hide]]
name = "The Lich"
reward = "Midnight Bargain Engraved Wand (minion)"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Return of the Rat"
reward = "Tavukai Coral Amulet (minion srs)"
drop_level = 0
info = "TODO"
