####################################################################################################
########## Gem: Top
####################################################################################################
[[valuable]]
name = "Desecrated Virtue"
reward = "Level 6 Awakened Support Gem Quality: +23% Corrupted"
drop_level = 0
info = "Aul, the Crystal King"

[[valuable]]
name = "The Cheater"
reward = "Level 6 Awakened Support Gem Quality: +20% Corrupted"
drop_level = 72
info = "Fortress (t17map)"

[[valuable]]
name = "Wealth and Power"
reward = "Level 4 Enlighten Corrupted"
drop_level = 68
info = "Citadel Map (t17map)"

####################################################################################################
########## Gem: All Season
####################################################################################################
[[all_season]]
name = "Doryani's Epiphany"
reward = "Random corrupted level 21 transfigured gem with 20% quality"
drop_level = 68
info = "Doryani's Machinarium Unique Map"

[[all_season]]
name = "Gemcutter's Mercy"
reward = "Exceptional Gem - (awakened or normal, empower, enhance, enchant)"
drop_level = 38
info = "Gem chests in the Azurite Mine."

[[all_season]]
name = "Home"
reward = "Exceptional Gem q1-20"
drop_level = 38
info = "Alleyways Ancient City, Arcade, Bazaar, Chateau, City Square, Crimson Township, Haunted Mansion, Residence, Siege, Sunken City, Tower. (awakened or normal, empower, enhance, enchant)"

[[all_season]]
name = "The Artist"
reward = "level 4 enhance Corrupted"
drop_level = 68
info = "Abomination (tier17 map)"

[[all_season]]
name = "The Enlightened"
reward = "Level 3 Enlighten"
drop_level = 60
info = "Basilica Map • Belfry Map • Crimson Temple Map • Defiled Cathedral Map • Ivory Temple Map • Lookout Map • Moon Temple Map • The Twilight Temple • Sanctuary Map • Temple Map"


####################################################################################################
########## Gem: Mix
####################################################################################################
[[good]]
name = "The Emptiness"
reward = "vaal breech gem"
drop_level = 80
info = "Appears to drop in maps (unique maps?) with the Mysterious Barrels sextant modifier."

[[good]]
name = "Brush Paint and Palette"
reward = "The artist card (enhance)"
drop_level = 0
info = "TODO"

[[good]]
name = "The Blessing of Moosh"
reward = "lvl 21 trans gem"
drop_level = 0
info = "TODO"

[[good]]
name = "The Bitter Blossom"
reward = "level 21 chaos gem q23 Corrupted"
drop_level = 0
info = "TODO"

[[good]]
name = "The Hook"
reward = "Level 21 Transfigured Gem 23% Quality Corrupted"
drop_level = 0
info = "TODO"

####################################################################################################
########## Gem: Gamble
####################################################################################################
[[gamble]]
name = "The Fox"
reward = "level 20 gem"
drop_level = 0
info = "TODO"

####################################################################################################
########## Gem: Hidden Unless SSF
####################################################################################################
[[hide]]
name = "A Chilling Wind"
reward = "21 vaal cold snap"
drop_level = 0
info = "TODO"

[[hide]]
name = "Deathly Designs"
reward = "level 21 trap gem 23q Corrupted"
drop_level = 72
info = "Ash Lessard"

[[hide]]
name = "The Magma Crab"
reward = "21 vaal molten shell"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Realm"
reward = "portal"
drop_level = 0
info = "TODO"

####################################################################################################
########## Gem: Hidden
####################################################################################################
[[hide]]
name = "Dialla's Subjugation"
reward = "support gem 23q Corrupted"
drop_level = 0
info = "todo"

[[hide]]
name = "Dying Anguish"
reward = "level 19 trans gem q19"
drop_level = 0
info = "TODO"

[[hide]]
name = "Gemcutter's Promise"
reward = "20q gem"
drop_level = 0
info = "TODO"

[[hide]]
name = "Gift of the Gemling Queen"
reward = "level 20 support gem"
drop_level = 68
info = "Crystal Ore Map • Dig Map • Excavation Map • Flooded Mine Map • Geode Map • Grotto Map"

[[hide]]
name = "The Cataclysm"
reward = "lvl 21 spell gem"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Doppelganger"
reward = "20q mirror arrow"
drop_level = 0
info = "TODO"

[[hide]]
name = "Volatile Power"
reward = "q20 vaal gem Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Wilted Rose"
reward = "level 21 aura gem Corrupted"
drop_level = 72
info = "Acton's Nightmare"