[variables]
colour_white = [255, 255, 255]
colour_red = [146, 29, 41]
txt_large = 45
txt_medium = 40
txt_small = 35
icon_circle = "Circle"

[[loots]]
name = "loot1"
SetFontSize = "&txt_large"
SetTextColor = "&colour_red"
SetBorderColor = "&colour_red"
SetBackgroundColor = "&colour_white"
PlayAlertSound = [1, 300]
PlayEffect = "Purple"
[loots.MinimapIcon]
size = 0
colour = "Purple"
shape = "&icon_circle"

[[loots]]
name = "loot2"
SetFontSize = "&txt_large"
SetTextColor = "&colour_red"
SetBorderColor = "&colour_red"
SetBackgroundColor = "&colour_white"
PlayAlertSound = [1, 300]
PlayEffect = "Purple"
[loots.MinimapIcon]
size = 0
colour = "Purple"
shape = "Star"

