[variables]
colour_white = [255, 255, 255]
colour_red = [146, 29, 41]
txt_large = 45
txt_medium = 40
txt_small = 35
icon_circle = "Circle"

[[loots]]
name = "loot1"
SetFontSize = "&txt_large"
SetTextColor = "&colour_red"
SetBorderColor = "&colour_red"
SetBackgroundColor = "&colour_white"
PlayAlertSound = [1, 300]
PlayEffect = "Purple"
[loots.MinimapIcon]
size = 0
colour = "Purple"
shape = "&icon_circle"

[[loots]]
name = "loot2"
SetFontSize = "&txt_large"
SetTextColor = "&colour_red"
SetBorderColor = "&colour_red"
SetBackgroundColor = "&colour_white"
PlayAlertSound = [1, 300]
PlayEffect = "Purple"
[loots.MinimapIcon]
size = 0
colour = "Purple"
shape = "Star"
















cards_expensive = [
"Deadly Joy", # The Torrent's Reclamation Cloth Belt
"Divine Justice", # Grand Spectrum jewel Corrupted
"The Endless Darkness", # Voidforge Infernal Sword
"Luminous Trove", # Voices Large Cluster Jewel Corrupted
"Monochrome", # CURRENTLY DISABLED
"The Price of Loyalty", # Skin of the Loyal Simple Robe (Two-Implicit Corrupted)
"The Sacrifice", # white 6link Sacrificial garb
"Auspicious Ambitions", # blue experimental 2x influence
"The Artist", # level 4 enhance Corrupted
"The Chosen", # Skin of the Lords Simple Robe
"The Garish Power", # unique jewel (not most expensive, but ok)
"The Greatest Intentions", # The Saviour Legion Sword Two-Implicit Corrupted
"The World Eater", # Starforge Infernal Sword
"Underground Forest", # CURRENTLY DISABLED

]


####################################################################################################
########## handpicked Cards
####################################################################################################

"Anarchy's Price", # Voltaxic Rift Spine Bow Corrupted
"Misery in Darkness", # Shroud of the Lightless Carnal Armour (abyss)
"Pride of the First Ones", # Farrul's Fur Triumphant Lamellar
"The Last One Standing", # Atziri's Disfavour Vaal Axe - 80+ Arena, Colosseum, Pit, Pit of the Chimera
"The Shieldbearer", # The Squire Elegant Round Shield - 70+ Citadel Map (t17map)
"The Soul", # Soul Taker Siege Axe
"Tranquillity", # Voltaxic Rift Spine Bow - 48+ Ashen Wood, Fields, Orchard, Peninsula, The Ashen Fields






##################################################
########## Always show: Personal favorites
##################################################
"A Fate Worse Than Death", # Cortex Synthesised Map Corrupted
"Abandoned Wealth", # 3x exalted
"Altered Perception"  # simulacrum (Megalomaniac mcluster, Split Personality Crimson Jewel, Voices lCluster)
"Alluring Bounty", # 10x exalted
"Demigod's Wager", # orb of annulment
"Eternal Bonds", # Replica Cortex Synthesised Map
"Ever-Changing", # 10x orb of unmaking
"Gemcutter's Mercy", # Exceptional Gem (awakened or normal, empower, enhance, enchant) - Gem chests in the Azurite Mine.
"Guardian's Challenge", # shaper guardian map
"Harmony of Souls", # 9x shrieking essence
"Home", # Exceptional Gem q1-20 (awakened or normal, empower, enhance, enchant) - 38+ Alleyways Ancient City, Arcade, Bazaar, Chateau, City Square, Crimson Township, Haunted Mansion, Residence, Siege, Sunken City, Tower
"Lingering Remnants", #  vaal temple map Corrupted
"Something Dark", # 83 blueprint fully revealed - Drops from Breachlords in Breachstones.
"The Artist", # level 4 enhance Corrupted
"The Cacophony", # 3x defening essence
"The Destination", # Watcher's Eye Prismatic Jewel Two-Implicit Corrupted - 81+ Beach Map • Channel Map • Shore Map • Fungal Hollow Map • Tropical Island Map
"The Eldritch Decay", # uber elder fragment
"The Eye of Terror", # Chayula's Flawless Breachstone
"The Fortunate", # 2x div
"The Hoarder", # exalted orb
"The Hunger", # Taste of Hate Sapphire Flask
"The Long Con", # elderslayers exalted orb
"The Professor", # The Putrid Cloister Museum Map
"The Rabbit's Foot", # 10x incursion vial
"The Rusted Bard", # 4x tainted mythic orb
"The Saint's Treasure", # 2x exalted
"The Seeker", # 3x orb of annulment
"The Scout", # 7x exalted
"The Transformation", # tainted mythic orb

##################################################
########## Always show: Gamble
##################################################
"Arrogance of the Vaal", # unique item Two-Implicit Corrupted
"Auspicious Ambitions", # blue experimental 2x influence
"Azyran's Reward", #  Prismatic Jewel Corrupted (can drop watcher)
"Boon of the First Ones", #beastiary item
"Brotherhood in Exile", # One With Nothing Small Cluster Jewel
"Chasing Risk", # Synthesis Item (can drop bottled fith)
"Council of Cats", # farrul item (often expensive)
"Fateful Meeting", # league specific item Two-Implicit Corrupted
"Haunting Shadows", # metamorph item (only drops in unique map)
"Hubris", # ring (can drop kalandras ring)
"Lucky Deck", # 10x stacked deck
"Peaceful Moments", # Timeless Jewel
"The Dreamer", # chayula item
"The Dungeon Master", # unique double influence belt (mageblood headhunter)
"The Eternal War", # timeless jewel
"The Prince of Darkness", # Elegant Hubris Timeless Jewel
"The Risk", # ventors gamble gold ring
"The Wretched", # belt (can drop mageblood and headhunter)
"Time-Lost Relic", # unique league specific item


####################################################################################################
########## Show Unless Rich (no filter needed)
####################################################################################################
"A Sea of Blue", # 13x alt
"Acclimatisation", # 20x alt
"Cameria's Cut", # scarab
"Chaotic Disposition", # 5x chaos
"Checkmate", # 76x simulacrum splinter
"Coveted Possession", # 5x regal
"Dementophobia", # 10x delerium orb
"Justified Ambition", # Synthesis Map
"Lucky Connections", # 20x fusings
"No Traces", # 10x orb of scouring
"Parasitic Passengers", # 10x incubator
"The Dreamland", # Poorjoy's Asylum Unique map
"The Encroaching Darkness", # Unique map
"The Heroic Shot", # 17x chromatic
"The Innocent", # 40x orb of regret
"The Inventor", # 10x vaal
"The Landing", # The Breachhead Unique map
"The Obscured", # breachstone
"The Price of Prescience"  # yellow vaal temple map Corrupted
"The Price of Protection", # yellow elder guardian map Corrupted
"The Side Quest", # 20x scouting report
"The Wolf's Legacy", # Vaults of Atziri Unique map
"The Wrath", # 10x chaos
"Three Faces in the Dark", # 3x chaos orb
"Three Voices", # 3x essence
"Vinia's Token", # 10x regret

##################################################
########## Show Unless Rich: Fishing
##################################################
"Baited Expectations", # fishing item unique
"The Catch", # fish rod
"The Fishmonger", # albino rhoa feather
"The Old Man", # yellow fishing rod
"The One That Got Away", # Replica Bated Breath Chain Belt


##################################################
########## Show Unless Rich: Gamble
##################################################
"Akil's Prophecy", # elegant round shield Two-Implicit Corrupted (squire chance)
"Atziri's Arsenal", #  weapon Corrupted
"Blind Venture", #  ring Corrupted
"Costly Curio", # double influenced unique
"Emperor's Luck", # 5x currency
"Glimmer of Hope", # gold ring
"Jack in the Box", # item
"Prejudice", # item - influenced
"Sambodhi's Wisdom", # q30 armour
"The Admirer", # atziri item (can drop disvaoir ad others)
"The Battle Born", # unique axe (can drop soultaker)
"The Body", # unique body armour
"The Breach", # unique breach item
"The Cache", # unique jewellery (good but not top)
"The Eye of the Dragon", # jewel Corrupted (not most expensive, but ok)
"The Forgotten Treasure", # unique double influenced leather belt (headhunter)
"The Forward Gaze", # unique replica item
"The Gambler", # div card
"The Gentleman", # unique sword Corrupted (Rakiata's Dance)
"The Mercenary", # unique shield Corrupted (squire chance)
"The Messenger", # harbringer piece
"The Shepherd's Sandals", # unique boots Two-Implicit Corrupted (Ralakesh's)
"The Undaunted", # nemesis item Corrupted (can drop headhunter)
"The Valkyrie", # nemesis item (can drop headhunter)
"The Void", # random card

##################################################
########## Show Unless Rich: misc
##################################################
"A Modest Request", # Megalomaniac Medium Cluster Jewel Corrupted
"Assassin's Gift", # Divinarius Imperial Skean Two-Implicit Corrupted
"Bijoux", # yellow cluster jewel
"Broken Promises", # blue 2x synt diamond ring
"Burning Blood", # Xoph's Blood Amber Amulet
"Desperate Crusade", # prism guardian shield
"Doryani's Epiphany", # Level 21 Transfigured Gem 20qual Corrupted
"Lachrymal Necrosis", # Corrupted yellow Jewel Implicit Modifier: Corrupted Blood cannot be inflicted on you
"Lethean Temptation", # Nebulis Void Sceptre
"Matryoshka", # rare onyx amulet Item Level: 85 Quality: +20% Influenced Item Four Anointments Incubating Talisman Item Corrupted
"Nook's Crown", # Bone Helmet Elder
"Silence and Frost", # The Pandemonius Jade Amulet
"The Academic", # Inspired Learning Crimson Jewel
"The Emptiness", # vaal breech gem
"The Escape", # Seven-League Step Rawhide Boots
"The Mad King", # vaal aspect
"The Patient", # the nurse
"The Polymath", # Astramentis Onyx Amulet
"The Sacrifice", # white 6link Sacrificial garb - 80+ The Temple of Atzoatl
"The Shortcut", # quicksilver flask of the cheeta
"The Strategist", # Inspired Learning Crimson Jewel Corrupted
"The Wedding Gift", # Arakaali's Fang
"The Twilight Moon", # the twilight moon map

"Monochrome", # CURRENTLY DISABLED
"More is Never Enough", # CURRENTLY DISABLED
"Rebirth and Renewal", # CURRENTLY DISABLED
"Underground Forest", # CURRENTLY DISABLED












####################################################################################################
########## Important Cards
####################################################################################################
"Beauty Through Death", # Atziri's Reflection Golden Buckler - 56+ K'aj A'alai, K'aj Q'ura, K'aj Y'ara'az (corrupt vaal temple)

"Fire Of Unknown Origin", # Nimis Topaz Ring - 81+ Academy, Residence


"The Chosen", # Skin of the Lords Simple Robe - Breach encounters such as in Clasped Hand
"The Demon", # Headhunter Leather Belt Two-Implicit Corrupted - Lord of the Grey (Belfry Map), Megaera (Crater Map), The Destroyer's Heart (Lava Lake Map)
"The Doctor", # Headhunter Leather Belt - 68+ SSSS
"The Endless Darkness", # Voidforge Infernal Sword - 81+ The Beachhead, Beachhead (unique harbringer maps), Delve. Harbinger Portals in Kirac's Memory of Phaaryl.
"The Fiend", # Headhunter Leather Belt Corrupted - 68+ Foundry Map • Laboratory Map • Shrine Map • Poorjoy's Asylum
"The Greatest Intentions", # The Saviour Legion Sword Two-Implicit Corrupted - Maven's Invitation: The Feared


"Beauty Through Death" "Deadly Joy" "Fire Of Unknown Origin" "Misery in Darkness" "Pride of the First Ones" "The Chosen" "The Demon" "The Doctor" "The Endless Darkness" "The Fiend" "The Greatest Intentions" "The Shieldbearer"

##################################################
########## Important Cards: Personal favorites
##################################################
"Brother's Gift", # 5x div
"Brother's Stash", # 5x exalted
"Choking Guilt", # Stranglegasp Onyx Amulet - 80+ The Infinite Hunger
"Darker Half", # 5x eldricht Exalted
"Desecrated Virtue", # Level 6 Awakened Support Gem Quality: +23% Corrupted - Aul, the Crystal King
"Divine Beauty", # 7x div
"Divine Justice", # Grand Spectrum jewel Corrupted - 56+ Armourer's Strongbox
"House of Mirrors", # 1x Mirror of Kalandra - 78+ The Alluring Abyss (uber atziri)
"I See Brothers", # 2x fracturing orb - 68+ various map bosses
"Love Through Ice", # Unnatural Instinct Two-Implicit Corrupted - Veritania, The Redeemer (conquerer)
"Luminous Trove", # Voices Large Cluster Jewel Corrupted - 68+ Aul, the Crystal King
"Seven Years Bad Luck", # 1x Mirror shard - 35+ Crimson Temple Map • Defiled Cathedral Map
"Succor of the Sinless", # Bottled Faith Sulphur Flask - 79+ Sanctuary (t17map)
"The Apothecary", # Mageblood Heavy Belt - 75+ Crimson Temple Map • Crimson Township Map • Defiled Cathedral Map • Haunted Mansion Map
"The Card Sharp", # divination scarab
"The Cheater", # Level 6 Awakened Support Gem Quality: +20% Corrupted - Fortress (t17map)
"The Dragon's Heart", # Level 4 Empower Corrupted - 78+ Fortress (t17map)
"The Enlightened", # Level 3 Enlighten - 60+ Basilica Map • Belfry Map • Crimson Temple Map • Defiled Cathedral Map • Ivory Temple Map • Lookout Map • Moon Temple Map • The Twilight Temple • Sanctuary Map • Temple Map

"The Gulf", # Thread of Hope crimson Jewel Two-Implicit Corrupted - 86+ Uber Elder only
"The Immortal", # house of mirrors - 35+ Hall of Grandmasters
"The Insane Cat", # Mageblood Heavy Belt corrupted - 68+ Drops from Omniphobia and Kosis in map areas affected by Delirium.
"The Price of Devotion", # Mageblood Heavy Belt Quality: +20% Two-Implicit Corrupted - 75+ Uber Atziri.
"The Progeny of Lunaris", # Dying Sun Ruby Flask - 81+ Helial, the Day Unending (The Twilight Temple Moon Temple Map), Khor, Sister of Shadows (Cold River Map), Sebbert, Crescent's Point (Moon Temple Map), Selenia, the Endless Night (The Twilight Temple Moon Temple Map)
"The Samurai's Eye", # Watcher's Eye Prismatic Jewel - 81 Ziggurat Map (t17map)
"The Sephirot", # 10x div
"Unrequited Love", # 19x Mirror Shard - 35+ The Temple of Decay Level 1 • Maze Map • Vaal Pyramid Map • Vaults of Atziri • Vaal Temple Map
"Wealth and Power", # Level 4 Enlighten Corrupted - Citadel Map (t17map)

