[variables]
colour_white = [255, 255, 255]
colour_red = [146, 29, 41]
txt_large = 45
txt_medium = 40
txt_small = 35

[epic]
font_size = "&txt_large"
text_colour = "&colour_red"
border_colour = "&colour_red"
background_colour = "&colour_white"
alert_sound = [1, 300]
effect = "Purple"
minimap_icon = [0, "Purple", "Star"]