
####################################################################################################
########## Favorite Cards
####################################################################################################
[[favorite]]
name = "Brother's Gift"
reward = "5x div"
drop_level = 68
info = "Cemetery Map • Grave Trough Map • Graveyard Map"

[[favorite]]
name = "Desecrated Virtue"
reward = "Level 6 Awakened Support Gem Quality: +23% Corrupted"
drop_level = 0
info = "Aul, the Crystal King"

[[favorite]]
name = "Divine Beauty"
reward = "7x div"
drop_level = 68
info = "Drops from Merveil in both Underground Sea Map and Maelström of Chaos"

[[favorite]]
name = "Gemcutter's Mercy"
reward = "Exceptional Gem - (awakened or normal, empower, enhance, enchant)"
drop_level = 38
info = "Gem chests in the Azurite Mine."

[[favorite]]
name = "Home"
reward = "Exceptional Gem q1-20"
drop_level = 38
info = "Alleyways Ancient City, Arcade, Bazaar, Chateau, City Square, Crimson Township, Haunted Mansion, Residence, Siege, Sunken City, Tower. (awakened or normal, empower, enhance, enchant)"

[[favorite]]
name = "House of Mirrors"
reward = "1x Mirror of Kalandra"
drop_level = 78
info = "The Alluring Abyss (uber atziri)"

[[favorite]]
name = "I See Brothers"
reward = "2x fracturing orb"
drop_level = 68
info = "various map bosses"

[[favorite]]
name = "Seven Years Bad Luck"
reward = "1x Mirror shard"
drop_level = 35
info = "Crimson Temple Map • Defiled Cathedral Map"

[[favorite]]
name = "Succor of the Sinless"
reward = "Bottled Faith Sulphur Flask"
drop_level = 79
info = "Sanctuary (t17map)"

[[favorite]]
name = "The Apothecary"
reward = "Mageblood Heavy Belt"
drop_level = 75
info = "Crimson Temple Map • Crimson Township Map • Defiled Cathedral Map • Haunted Mansion Map"

[[favorite]]
name = "The Cheater"
reward = "Level 6 Awakened Support Gem Quality: +20% Corrupted"
drop_level = 72
info = "Fortress (t17map)"

[[favorite]]
name = "The Destination"
reward = "Watcher's Eye Prismatic Jewel Two-Implicit Corrupted"
drop_level = 81
info = "Beach Map • Channel Map • Shore Map • Fungal Hollow Map • Tropical Island Map"

[[favorite]]
name = "The Dragon's Heart"
reward = "Level 4 Empower Corrupted"
drop_level = 78
info = "Fortress (t17map)"

[[favorite]]
name = "The Enlightened"
reward = "Level 3 Enlighten"
drop_level = 60
info = "Basilica Map • Belfry Map • Crimson Temple Map • Defiled Cathedral Map • Ivory Temple Map • Lookout Map • Moon Temple Map • The Twilight Temple • Sanctuary Map • Temple Map"

[[favorite]]
name = "The Gulf"
reward = "Thread of Hope crimson Jewel Two-Implicit Corrupted"
drop_level = 86
info = "Uber Elder only (Passives in Radius can be Allocated without being connected to your tree)"

[[favorite]]
name = "The Immortal"
reward = "House of Mirrors Card"
drop_level = 35
info = "The Hall of Grandmasters"

[[favorite]]
name = "The Insane Cat"
reward = "Mageblood Heavy Belt corrupted"
drop_level = 68
info = "Drops from Omniphobia and Kosis in map areas affected by Delirium."

[[favorite]]
name = "The Price of Devotion"
reward = "Mageblood Heavy Belt Quality +20% Two-Implicit Corrupted"
drop_level = 75
info = "Uber Atziri."

[[favorite]]
name = "The Samurai's Eye"
reward = "Watcher's Eye Prismatic Jewel"
drop_level = 81
info = "Ziggurat Map (t17map)"

[[favorite]]
name = "The Sephirot"
reward = "10x div"
drop_level = 35
info = "Dominus, Ascendant Excellis Aurafix The Hallowed Husk The Hallowed Husk The High Templar"

[[favorite]]
name = "Unrequited Love"
reward = "19x Mirror Shard"
drop_level = 35
info = "The Temple of Decay Level 1 • Maze Map • Vaal Pyramid Map • Vaults of Atziri • Vaal Temple Map"

[[favorite]]
name = "Wealth and Power"
reward = "Level 4 Enlighten Corrupted"
drop_level = 68
info = "Citadel Map (t17map)"


####################################################################################################
########## High Value Cards
####################################################################################################
[[favorite]]
name = "Love Through Ice"
reward = "Two-Implicit Corrupted Unnatural Instinct Viridian Jewel - (Allocated Small Passive Skills in Radius grant nothing
Grants all bonuses of Unallocated Small Passive Skills in Radius) can be excellent with the parandus pact"
drop_level = 54
info = "Veritania, The Redeemer (conquerer)"







####################################################################################################
########## Favorite cards I always want to loot (I'm mostly SSF)
####################################################################################################

