
[[good]]
name = "Doryani's Epiphany"
reward = "Random corrupted level 21 transfigured gem with 20% quality"
drop_level = 68
info = "Doryani's Machinarium Unique Map"





[[good]]
name = "The Union"
reward = "10x gemcutters prism"
drop_level = 23
info = "The Fellshrine Ruins (Act 7) • Cemetery Map • Grave Trough Map • Graveyard Map"



[[hide]]
name = "The Emptiness"
reward = "vaal breech gem"
drop_level = 80
info = "Appears to drop in maps (unique maps?) with the Mysterious Barrels sextant modifier."




####################################################################################################
########## Hidden Gem related Cards - not all of these are bad
####################################################################################################

[[hide]]
name = "A Chilling Wind"
reward = "21 vaal cold snap"
drop_level = 0
info = "TODO"

[[good]]
name = "Deathly Designs"
reward = "level 21 trap gem 23q Corrupted"
drop_level = 72
info = "Ash Lessard"

[[hide]]
name = "Dialla's Subjugation"
reward = "support gem 23q Corrupted"
drop_level = 0
info = "todo"

[[hide]]
name = "Dying Anguish"
reward = "level 19 trans gem q19"
drop_level = 0
info = "TODO"

[[good]]
name = "Gift of the Gemling Queen"
reward = "level 20 support gem"
drop_level = 68
info = "Crystal Ore Map • Dig Map • Excavation Map • Flooded Mine Map • Geode Map • Grotto Map"

[[hide]]
name = "Terrible Secret of Space"
reward = "level 21 trans golem gem Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Bitter Blossom"
reward = "level 21 chaos gem q23 Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Blessing of Moosh"
reward = "lvl 21 trans gem"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Cataclysm"
reward = "lvl 21 spell gem"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Doppelganger"
reward = "20q mirror arrow"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Fox"
reward = "level 20 gem"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Hook"
reward = "Level 21 Transfigured Gem 23% Quality Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Realm"
reward = "portal"
drop_level = 0
info = "TODO"

[[hide]]
name = "Volatile Power"
reward = "q20 vaal gem Corrupted"
drop_level = 0
info = "TODO"

