####################################################################################################
########## Favorite Good Value Cards
####################################################################################################
[[favorite]]
name = "Abandoned Wealth"
reward = "3x exalted"
drop_level = 68
info = "Mao Kun map"

[[favorite]]
name = "Alluring Bounty"
reward = "10x exalted"
drop_level = 68
info = "The Apex of Sacrifice • The Alluring Abyss"

[[favorite]]
name = "Brother's Stash"
reward = "5x exalted"
drop_level = 68
info = "Cemetery Map • Grave Trough Map • Graveyard Map"

[[favorite]]
name = "Darker Half"
reward = "5x eldricht Exalted"
drop_level = 81
info = "Drops when receiving Currency rewards from Delirium layers in maps (from Delirium Mirror or Delirium Orbs) and in Simulacrum."

[[good]]
name = "Ever-Changing"
reward = "10x Orb of Unmaking"
drop_level = 68
info = "Drops in maps opened via Kirac missions."

[[favorite]]
name = "The Eye of Terror"
reward = "Chayula's Flawless Breachstone"
drop_level = 68
info = "It That Fled"

[[favorite]]
name = "The Fortunate"
reward = "2x div"
drop_level = 68
info = "Ancient City Map • Arid Lake Map • Atoll Map • Beach Map • Burial Chambers Map • Caldera Map • Canyon Map • Desert Map • Desert Spring Map • Dry Sea Map • Dunes Map • Estuary Map • Fields Map • Jungle Valley Map • Leyline Map • Marshes Map • Mesa Map • Mineral Pools Map • Orchard Map • Peninsula Map • Plateau Map • Shore Map • Sulphur Vents Map • Terrace Map • Crater Map • Tropical Island Map"

[[favorite]]
name = "The Long Con"
reward = "Elderslayer's Exalted Orb"
drop_level = 80
info = "This card drops from Izaro's Treasure chests in the Eternal Labyrinth (Uber Lab) and Enriched Eternal Labyrinth."

[[good]]
name = "The Saint's Treasure"
reward = "2x Exalted Orb"
drop_level = 68
info = "Alleyways Map • Arcade Map • Bazaar Map • Ghetto Map • Port Map • Precinct Map"

[[good]]
name = "The Scout"
reward = "7x Exalted Orb"
drop_level = 68
info = "Ashen Wood Map • Bramble Valley Map • Dark Forest Map • Forbidden Woods Map • Jungle Valley Map • Lair Map • Ramparts Map • Spider Forest Map • Stagnation Map • Thicket Map • Tropical Island Map"

[[favorite]]
name = "The Transformation"
reward = "Tainted Mythic Orb"
drop_level = 68
info = "Drops from bosses with the 'transform_boss' monster tag."


####################################################################################################
########## Decent value Cards with few drop locations
####################################################################################################
[[good]]
name = "Magnum Opus"
reward = "Three-Implicit Synthesised Normal level 100 Item"
drop_level = 80
info = "Altered Distant Memory • Augmented Distant Memory • Twisted Distant Memory • Rewritten Distant Memory"




####################################################################################################
########## Decent value Cards
####################################################################################################





[[favorite]]
name = "Beauty Through Death"
reward = "Atziri's Reflection Golden Buckler"
drop_level = 56
info = "K'aj A'alai, K'aj Q'ura, K'aj Y'ara'az (corrupt vaal temple)"

[[good]]
name = "Deadly Joy"
reward = "The Torrent's Reclamation Cloth Belt"
drop_level = 68
info = "Poorjoy's Asylum"

[[favorite]]
name = "Fire Of Unknown Origin"
reward = "Nimis Topaz Ring"
drop_level = 81
info = "Academy, Residence"

[[good]]
name = "Misery in Darkness"
reward = "Shroud of the Lightless Carnal Armour (abyss)"
drop_level = 68
info = "Kurgal, the Blackblooded"

[[favorite]]
name = "The Chosen"
reward = "Skin of the Lords Simple Robe"
drop_level = 80
info = "Breach encounters such as in Clasped Hand"

[[favorite]]
name = "The Endless Darkness"
reward = "Voidforge Infernal Sword"
drop_level = 81
info = "The Beachhead, Beachhead (unique harbringer maps), Delve. Harbinger Portals in Kirac's Memory of Phaaryl."

[[good]]
name = "The Greatest Intentions"
reward = "The Saviour Legion Sword Two-Implicit Corrupted"
drop_level = 81
info = "Maven's Invitation: The Feared"

[[favorite]]
name = "The Last One Standing"
reward = "Atziri's Disfavour Vaal Axe"
drop_level = 80
info = "Arena, Colosseum, Pit, Pit of the Chimera"

[[favorite]]
name = "The Price of Loyalty"
reward = "Skin of the Loyal Simple Robe (Two-Implicit Corrupted)"
drop_level = 79
info = "Zilquapa, Architect of the Breach"

[[favorite]]
name = "The Shieldbearer"
reward = "The Squire Elegant Round Shield"
drop_level = 70
info = "Citadel Map (t17map)"

[[favorite]]
name = "The Soul"
reward = "Soul Taker Siege Axe"
drop_level = 68
info = "Cells Map • Core Map • Museum Map • Overgrown Shrine Map • Phantasmagoria Map • Sepulchre Map • Tower Map • Waste Pool Map"

[[favorite]]
name = "The World Eater"
reward = "Starforge Infernal Sword"
drop_level = 83
info = "Ghorr, the Grasping Maw"

[[favorite]]
name = "The Artist"
reward = "level 4 enhance Corrupted"
drop_level = 68
info = "Abomination (tier17 map)"

[[favorite]]
name = "The Eldritch Decay"
reward = "uber elder fragment"
drop_level = 81
info = "The Constrictor The Enslaver The Eradicator The Purifier"

[[favorite]]
name = "The Sacrifice"
reward = "white 6link Sacrificial garb"
drop_level = 80
info = "The Temple of Atzoatl"

[[good]]
name = "Guardian's Challenge"
reward = "Shaper Guardian Map"
drop_level = 91
info = "Sold by Kirac for 3x Cartographer's Chisel"

[[favorite]]
name = "Something Dark"
reward = "83 blueprint fully revealed"
drop_level = 75
info = "Drops from Breachlords in Breachstones."

[[good]]
name = "The Union"
reward = "10x gemcutters prism"
drop_level = 23
info = "The Fellshrine Ruins (Act 7) • Cemetery Map • Grave Trough Map • Graveyard Map"




####################################################################################################
########## Typically >100C in trade
####################################################################################################


####################################################################################################
########## Typically 50-100ish in trade or valuable item or has few drop places
####################################################################################################



####################################################################################################
########## Typically 10-50ish in trade
####################################################################################################
