####################################################################################################
########## Good Value
####################################################################################################
[[good]]
name = "Auspicious Ambitions"
reward = "Experimented Item Level: 100 Double-Influenced"
drop_level = 73
info = "Drops from the regular and uber versions of Maven, Exarch, Eater, and Uber Elder."

[[good]]
name = "Brother's Stash"
reward = "5x exalted"
drop_level = 68
info = "Cemetery Map • Grave Trough Map • Graveyard Map"

[[good]]
name = "Darker Half"
reward = "5x eldricht Exalted"
drop_level = 81
info = "Drops when receiving Currency rewards from Delirium layers in maps (from Delirium Mirror or Delirium Orbs) and in Simulacrum."

[[good]]
name = "Matryoshka"
reward = "rare onyx amulet Item Level: 85 Quality: +20% Influenced Item Four Anointments Incubating Talisman Item Corrupted"
drop_level = 68
info = "Unravelling Horror"

[[good]]
name = "The Doctor"
reward = "Headhunter Leather Belt"
drop_level = 68
info = "Abomination Map • Burial Chambers Map • The Putrid Cloister • Phantasmagoria Map • Sepulchre Map • Spider Forest Map • Waste Pool Map"

[[good]]
name = "The Fiend"
reward = "Headhunter Leather Belt Corrupted"
drop_level = 68
info = "Foundry Map • Laboratory Map • Shrine Map • Poorjoy's Asylum"

[[good]]
name = "The Greatest Intentions"
reward = "The Saviour Legion Sword Two-Implicit Corrupted"
drop_level = 81
info = "Maven's Invitation: The Feared (shaper)"

[[good]]
name = "The Long Con"
reward = "Elderslayer's Exalted Orb"
drop_level = 80
info = "This card drops from Izaro's Treasure chests in the Eternal Labyrinth (Uber Lab) and Enriched Eternal Labyrinth."

[[good]]
name = "The Price of Loyalty"
reward = "Skin of the Loyal Simple Robe (Two-Implicit Corrupted)"
drop_level = 79
info = "Zilquapa, Architect of the Breach"

[[good]]
name = "The Sacrifice"
reward = "white 6link Sacrificial garb"
drop_level = 80
info = "The Temple of Atzoatl"


####################################################################################################
########## All Season Content Cards
####################################################################################################

[[good]]
name = "A Fate Worse Than Death"
reward = "Cortex Synthesised Map Corrupted"
drop_level = 78
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer, Sirus Awakener of Worlds"

[[favorite]]
name = "Altered Perception"
reward = "simulacrum (can drop Megalomaniac mcluster, Split Personality Crimson Jewel, Voices (Cluster)"
drop_level = 68
info = "Uhtred Covetous Traitor"

[[good]]
name = "Eternal Bonds"
reward = "Replica Cortex Synthesised Map"
drop_level = 78
info = "Drops from Map Reward Chests in Heist Contracts and Blueprints"

[[hide]]
name = "Sambodhi's Vow"
reward = "mortal fragment (uber atziri)"
drop_level = 70
info = "Can drop from members of the Immortal Syndicate."

[[favorite]]
name = "Something Dark"
reward = "83 blueprint fully revealed"
drop_level = 75
info = "Drops from Breachlords in Breachstones."

[[favorite]]
name = "The Eldritch Decay"
reward = "uber elder fragment"
drop_level = 81
info = "The Constrictor The Enslaver The Eradicator The Purifier"


####################################################################################################
########## Content Cards
####################################################################################################
[[hide]]
name = "Azure Rage"
reward = "Random Punishing Magic tier 16 map (phsyical reflect)"
drop_level = 81
info = "Factory Map • Port Map"

[[favorite]]
name = "Dementophobia"
reward = "10x Delerium Orb"
drop_level = 68
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer, Venarius"
 
[[hide]]
name = "Disdain"
reward = "delerium orb"
drop_level = 44
info = "Can drop after completing any Maven's Invitation, including Quest ones."

[[good]]
name = "Guardian's Challenge"
reward = "Shaper Guardian Map"
drop_level = 81
info = "Sold by Kirac for 3x Cartographer's Chisel"

[[favorite]]
name = "Justified Ambition"
reward = "Synthesis Map"
drop_level = 81
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer"

[[hide]]
name = "Last Hope"
reward = "Mortal Hope (opens vaal areas and buffs map quality)"
drop_level = 68
info = "Atziri, Queen of the Vaal"

[[hide]]
name = "Left to Fate"
reward = "Random unidentified corrupted tier 16 Rare map"
drop_level = 73
info = "Forking River Map • Ramparts Map"

[[favorite]]
name = "Lingering Remnants"
reward = "vaal temple map Corrupted"
drop_level = 78
info = "Drops in a lot of maps"

[[good]]
name = "Scholar of the Seas"
reward = "Mao Kun Unique map"
drop_level = 68
info = "The Brine King's Reef • Coves Map • Reef Map • Strand Map • Whakawairua Tuahu"

[[good]]
name = "The Dreamland"
reward = "Poorjoy's Asylum Unique map"
drop_level = 68
info = "Drops from Cartographer's Strongboxes."

[[good]]
name = "The Landing"
reward = "The Breachhead Unique map"
drop_level = 73
info = "Shore Map • Mao Kun • Strand Map • Whakawairua Tuahu"

[[favorite]]
name = "The Price of Prescience"
reward = "Vaal Temple Map T16 Delirium: 100% Corrupted"
drop_level = 78
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer"

[[good]]
name = "The Price of Protection"
reward = "Elder Guardian Occupied Map T: 14 to 16 Modifiers: 8 Corrupted"
drop_level = 81
info = "Drops from Invasion bosses or Vaal side area bosses."

[[good]]
name = "The Professor"
reward = "The Putrid Cloister Unique Museum Map"
drop_level = 68
info = "Academy Map • Laboratory Map • Museum Map • Scriptorium Map"

[[hide]]
name = "The Puzzle"
reward = "5x breech stone splinter"
drop_level = 68
info = "The Puzzle can drop from Beyond demons."

[[good]]
name = "The Wolf's Legacy"
reward = "Vaults of Atziri Unique map"
drop_level = 68
info = "This card drops from Izaro's Treasure chests, Labyrinth Troves, or Silver Key caches in the Eternal Labyrinth or Enriched Eternal Labyrinth. Still requires verification if it can drop in Merciless Labyrinth."

[[good]]
name = "Treasure Hunter"
reward = "Vaults of Atziri Unique map"
drop_level = 68
info = "Museum Map • Relic Chambers Map • Vaults of Atziri • Vault Map"


####################################################################################################
########## Non-Drop cards
####################################################################################################

[[good]]
name = "Ever-Changing"
reward = "10x Orb of Unmaking"
drop_level = 68
info = "Drops in maps opened via Kirac missions."

[[hide]]
name = "Assassin's Gift"
reward = "Divinarius Imperial Skean Two-Implicit Corrupted"
drop_level = 68
info = "doesn't drop, only from gamble cards"

[[hide]]
name = "More is Never Enough"
reward = "?"
drop_level = 0
info = "CURRENTLY DISABLED"

[[hide]]
name = "Rebirth and Renewal"
reward = "?"
drop_level = 0
info = "CURRENTLY DISABLED"

[[favorite]]
name = "Underground Forest"
reward = "Sextants, which don't crop after 234"
drop_level = 0
info = "CURRENTLY DISABLED"

[[hide]]
name = "Winter's Embrace"
reward = "Three-implicit synthesised Circle of Fear Sapphire Ring"
drop_level = 68
info = "doesn't drop, only from gamble cards"

####################################################################################################
########## Useful cards
####################################################################################################
[[good]]
name = "Abandoned Wealth"
reward = "3x exalted"
drop_level = 68
info = "Mao Kun map"

[[good]]
name = "Alluring Bounty"
reward = "10x exalted"
drop_level = 68
info = "The Apex of Sacrifice • The Alluring Abyss"

[[good]]
name = "Coveted Possession"
reward = "5x Regal Orb"
drop_level = 23
info = "The Catacombs • The Ossuary (Act 5) • The Ossuary (Act 10) • Bone Crypt Map • Sanctuary Map • Ziggurat Map"

[[favorite]]
name = "Demigod's Wager"
reward = "Orb of Annulment"
drop_level = 35
info = "The Cleansing Light"

[[favorite]]
name = "Harmony of Souls"
reward = "9x shrieking essence"
drop_level = 68
info = "Abomination Map Can drop from versions of Doedre, Maligaro, and Shavronne in Sepulchre Map, Overgrown Shrine Map, and Cells Map respectively, as well as Abomination Map"

[[good]]
name = "No Traces"
reward = "10x Orb of Scouring"
drop_level = 23
info = "The Ossuary (Act 5) • The Reliquary (Act 10) • The Ossuary (Act 10) • Mausoleum Map • Relic Chambers Map • Sepulchre Map • Ziggurat Map"

[[good]]
name = "Parasitic Passengers"
reward = "10x Incubator"
drop_level = 68
info = "Arachnid Tomb Map • Channel Map • Infested Valley Map"

[[good]]
name = "The Cartographer"
reward = "10x cartographers chisel"
drop_level = 39
info = "Drops from Cartographer's Strongboxes."

[[good]]
name = "The Eye of Terror"
reward = "Chayula's Flawless Breachstone"
drop_level = 68
info = "It That Fled"

[[good]]
name = "The Fortunate"
reward = "2x div"
drop_level = 68
info = "Ancient City Map • Arid Lake Map • Atoll Map • Beach Map • Burial Chambers Map • Caldera Map • Canyon Map • Desert Map • Desert Spring Map • Dry Sea Map • Dunes Map • Estuary Map • Fields Map • Jungle Valley Map • Leyline Map • Marshes Map • Mesa Map • Mineral Pools Map • Orchard Map • Peninsula Map • Plateau Map • Shore Map • Sulphur Vents Map • Terrace Map • Crater Map • Tropical Island Map"

[[good]]
name = "The Innocent"
reward = "40x Orb of Regret"
drop_level = 23
info = "The Chamber of Innocence • Basilica Map • Defiled Cathedral Map • Sanctuary Map"

[[good]]
name = "The Saint's Treasure"
reward = "2x Exalted Orb"
drop_level = 68
info = "Alleyways Map • Arcade Map • Bazaar Map • Ghetto Map • Port Map • Precinct Map"

[[good]]
name = "The Scout"
reward = "7x Exalted Orb"
drop_level = 68
info = "Ashen Wood Map • Bramble Valley Map • Dark Forest Map • Forbidden Woods Map • Jungle Valley Map • Lair Map • Ramparts Map • Spider Forest Map • Stagnation Map • Thicket Map • Tropical Island Map"

[[favorite]]
name = "The Seeker"
reward = "3x Orb of Annulment"
drop_level = 35
info = "The Temple of Atzoatl"

[[favorite]]
name = "The Side Quest"
reward = "20x Scouting Report"
drop_level = 69
info = "Alleyways Map • Arachnid Tomb Map • Armoury Map • Castle Ruins Map • Forking River Map • Iceberg Map • Infested Valley Map • Mineral Pools Map • Siege Map • Primordial Blocks Map"

[[good]]
name = "The Transformation"
reward = "Tainted Mythic Orb"
drop_level = 68
info = "Drops from bosses with the 'transform_boss' monster tag."

####################################################################################################
########## Decent value Cards with few drop locations
####################################################################################################
[[hide]]
name = "Broken Promises"
reward = "Two-implicit synthesised item level 87 Normal Diamond Ring"
drop_level = 80
info = "Eater of Souls, Tolman the Exhumer"

[[good]]
name = "Deadly Joy"
reward = "two-implicit corrupted The Torrent's Reclamation Cloth Belt"
drop_level = 68
info = "Poorjoy's Asylum"

[[hide]]
name = "Imperfect Memories"
reward = "Random three-implicit synthesised item level 100 rare jewellery"
drop_level = 80
info = "Venarius (Synth Cortex Map)"

[[good]]
name = "Magnum Opus"
reward = "Three-Implicit Synthesised Normal level 100 Item"
drop_level = 80
info = "Altered Distant Memory • Augmented Distant Memory • Twisted Distant Memory • Rewritten Distant Memory"

[[good]]
name = "Misery in Darkness"
reward = "Shroud of the Lightless Carnal Armour (abyss)"
drop_level = 68
info = "Kurgal, the Blackblooded (delve boss)"

[[good]]
name = "The Artist"
reward = "level 4 enhance Corrupted"
drop_level = 68
info = "Abomination (tier17 map)"

[[hide]]
name = "The Astromancer"
reward = "two-implicit corrupted The Eternity Shroud Blood Raiment"
drop_level = 81
info = "Corpse Stitcher (heist lab thing)"

[[good]]
name = "The Chosen"
reward = "Skin of the Lords Simple Robe"
drop_level = 80
info = "Breach encounters such as in Clasped Hand"

[[good]]
name = "The Shieldbearer"
reward = "The Squire Elegant Round Shield"
drop_level = 70
info = "Citadel Map (t17map)"

[[good]]
name = "The World Eater"
reward = "Starforge Infernal Sword"
drop_level = 83
info = "Ghorr, the Grasping Maw"


####################################################################################################
########## Decent value Cards
####################################################################################################
[[good]]
name = "Anarchy's Price"
reward = "Voltaxic Rift Spine Bow Corrupted"
drop_level = 48
info = "This item can drop from Rogue Exiles."

[[favorite]]
name = "The Last One Standing"
reward = "Atziri's Disfavour Vaal Axe"
drop_level = 80
info = "Arena, Colosseum, Pit, Pit of the Chimera"

[[hide]]
name = "The Mad King"
reward = "Vaal Aspect (drops from vaal bosses, can be combined to The Adorned Crimson Jewel - (50-150)% increased Effect of Jewel Socket Passive Skills containing Corrupted Magic Jewels"
drop_level = 68
info = "Caldera Map • Colosseum Map • Dark Forest Map • Reef Map"

[[favorite]]
name = "The Nurse"
reward = "The Doctor"
drop_level = 30
info = "Abomination, Carcass, Cells, Core, Scriptorium, Shavronne's Tower, The Harvest, The Rotting Core, Tower"

[[favorite]]
name = "The Soul"
reward = "Soul Taker Siege Axe"
drop_level = 68
info = "Cells Map • Core Map • Museum Map • Overgrown Shrine Map • Phantasmagoria Map • Sepulchre Map • Tower Map • Waste Pool Map"

[[good]]
name = "Tranquillity"
reward = "Voltaxic Rift Spine Bow"
drop_level = 48
info = "Ashen Wood, Fields, Orchard, Peninsula, The Ashen Fields"

####################################################################################################
########## Cheap Cards that don't drop in a lot of places
####################################################################################################

[[good]]
name = "Chaotic Disposition"
reward = "5x Chaos Orb"
drop_level = 23
info = "Poorjoy's Asylum"

[[hide]]
name = "Nook's Crown"
reward = "Elder influenced item level 100 Rare Bone Helmet"
drop_level = 0
info = "Catarina Master of Undeath (Investigation boss)"

[[hide]]
name = "Silence and Frost"
reward = "The Pandemonius Jade Amulet"
drop_level = 70
info = "Farrul, First of the Plains"

[[hide]]
name = "The Escape"
reward = "Seven-League Step Rawhide Boots"
drop_level = 56
info = "Drops from Breachlords in Breachstones."

[[favorite]]
name = "The Rusted Bard"
reward = "4x Tainted Mythic Orb"
drop_level = 68
info = "The Vinktar Square"


####################################################################################################
########## Cheap Cards with some interest
####################################################################################################
[[favorite]]
name = "Brotherhood in Exile"
reward = "One With Nothing Small Cluster Jewel (Adds Hollow Palm Technique)"
drop_level = 68
info = "Chateau Map • Conservatory Map • Orchard Map • Plaza Map"

[[good]]
name = "The Heroic Shot"
reward = "17x chromatic"
drop_level = 23
info = "Can drop from Arcanist's Strongboxes"

[[good]]
name = "The Hoarder"
reward = "Exalted Orb"
drop_level = 68
info = "Maelström of Chaos • Mineral Pools Map • Underground Sea Map • Vaults of Atziri • Vault Map"

[[good]]
name = "The Inventor"
reward = "10x Vaal Orb"
drop_level = 23
info = "The Ancient Pyramid • The Temple of Decay Level 1 • The Temple of Decay Level 2 • Maze Map • Doryani's Machinarium • Vaal Pyramid Map • Vaults of Atziri • Vaal Temple Map"

[[good]]
name = "The Rabbit's Foot"
reward = "10x Incursion Vial"
drop_level = 50
info = "Bone Crypt Map • Citadel Map • Cursed Crypt Map • The Coward's Trial • Ziggurat Map"

[[favorite]]
name = "The Patient"
reward = "the nurse"
drop_level = 68
info = "Armoury Map • Arsenal Map • Colonnade Map • Promenade Map"

####################################################################################################
########## Gamble tier
####################################################################################################
[[good]]
name = "Akil's Prophecy"
reward = "elegant round shield Two-Implicit Corrupted (squire chance)"
drop_level = 70
info = "Alva's"

[[good]]
name = "Emperor's Luck"
reward = "5x currency"
drop_level = 23
info = "The Imperial Gardens • The High Gardens • Courtyard Map • Gardens Map • Orchard Map • Terrace Map"

[[good]]
name = "Lucky Deck"
reward = "10x stacked deck"
drop_level = 74
info = "Ziggurat Map"

[[hide]]
name = "The Gambler"
reward = "divination card"
drop_level = 0
info = "todo"

[[good]]
name = "The Tireless Extractor"
reward = "10x oil"
drop_level = 68
info = "Factory Map • Fortress Map • Port Map • Silo Map"

####################################################################################################
########## Might not drop good scarabs
####################################################################################################
[[favorite]]
name = "Cameria's Cut"
reward = "Scarab"
drop_level = 68
info = "Cameria the Coldblooded"

[[good]]
name = "Hubris"
reward = "Ring (can drop kalandras ring)"
drop_level = 23
info = "Can drop from Jeweller's Strongboxes."

[[good]]
name = "Jack in the Box"
reward = "item"
drop_level = 23
info = "The City of Sarn • The Ebony Barracks • The Slums • The Marketplace • The Battlefront • The Docks • The Sarn Ramparts • The Solaris Concourse • The Harbour Bridge • The Grand Promenade • The Lunaris Concourse • The Quay • The Grain Gate • Arsenal Map • Colonnade Map • Ghetto Map • Port Map • Precinct Map • Promenade Map"

[[hide]]
name = "Man With Bear"
reward = "bestiary scarab"
drop_level = 68
info = "Barrows Map • Cemetery Map"

[[favorite]]
name = "The Card Sharp"
reward = "divination scarab"
drop_level = 68
info = "alva missions + Alva's Memory of Reverse Incursion."

[[hide]]
name = "The Deal"
reward = "cartography scarab"
drop_level = 68
info = "Cameria the Coldblooded"
