
####################################################################################################
########## Cheap Cards that don't drop in a lot of places
####################################################################################################
[[hide]]
name = "Silence and Frost"
reward = "The Pandemonius Jade Amulet"
drop_level = 70
info = "Farrul, First of the Plains"

[[hide]]
name = "The Escape"
reward = "Seven-League Step Rawhide Boots"
drop_level = 56
info = "Drops from Breachlords in Breachstones."


####################################################################################################
########## Build related cards that are hidden by default
####################################################################################################

[[hide]]
name = "Brush, Paint and Palette"
reward = "The Artist card - (The Artists awards enhance)"
drop_level = 68
info = "Doedre the Defiler, Doedre the Defiler, Erythrophagia, Headmistress Braeta, Portentia, the Foul, Prodigy of Hexes"

[[hide]]
name = "Burning Blood"
reward = "corrupted Xoph's Blood Amber Amulet"
drop_level = 70
info = "Forge of the Phoenix Lava Chamber"

[[hide]]
name = "Dark Dreams"
reward = "yellow elder influence bone helmet"
drop_level = 0
info = "todo"

[[hide]]
name = "Gift of Asenath"
reward = "two-implicit corrupted Asenath's Gentle Touch Silk Gloves"
drop_level = 68
info = "Crystal Ore Map • Dig Map • Excavation Map • Flooded Mine Map • Geode Map • Grotto Map"

[[hide]]
name = "Lethean Temptation"
reward = "Nebulis Void Sceptre"
drop_level = 0
info = "Only from gamble cards"

[[hide]]
name = "The Spark and the Flame"
reward = "bereks respite two stone ring"
drop_level = 23
info = "Atoll Map • Plateau Map • Siege Map"

[[hide]]
name = "The Wedding Gift"
reward = "Arakaali's Fang Fiend Dagger"
drop_level = 52
info = "Overgrown Ruin Map • Sunken City Map"

[[hide]]
name = "The White Knight"
reward = "Normal Six-Link Astral Plate Item Level: 100 Crusader Item"
drop_level = 0
info = "Trial of Stinging Doubt"


####################################################################################################
########## Ultra Mega Hipster build related cards that are hidden by default
####################################################################################################
[[hide]]
name = "Draped in Dreams"
reward = "blue 6link astral plate influenced"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Academic"
reward = "Inspired Learning Crimson Jewel - (With 4 Notables Allocated in Radius, When you Kill a Rare monster, you gain 1 of its Modifiers for 20 seconds)"
drop_level = 38
info = "Academy Map • Museum Map • Scriptorium Map"

[[hide]]
name = "The Wilted Rose"
reward = "level 21 aura gem Corrupted"
drop_level = 72
info = "Acton's Nightmare"

[[hide]]
name = "Who Asked"
reward = "Dictator's Weapon Item Level: 83 Fractured - (% physical damage and accuracy rating)"
drop_level = 80
info = "Fortress Map • Foundry Map • Forge of the Phoenix Map • Silo Map May drop from other Forge_Area tag maps"

####################################################################################################
########## Fishing related cards that are hidden by default
####################################################################################################

[[hide]]
name = "The Vast"
reward = "Song of the Sirens Fishing Rod"
drop_level = 23
info = "Coral Ruins Map • Coves Map • Reef Map"

