cards_epic

"Beauty Through Death" # Atziri's Reflection Golden Buckler - 56+ K'aj A'alai, K'aj Q'ura, K'aj Y'ara'az (corrupt vaal temple)
"Deadly Joy" # The Torrent's Reclamation Cloth Belt
"Fire Of Unknown Origin" # Nimis Topaz Ring - 81+ Academy, Residence
"Misery in Darkness" # Shroud of the Lightless Carnal Armour (abyss)
"Pride of the First Ones" # Farrul's Fur Triumphant Lamellar
"The Chosen" # Skin of the Lords Simple Robe - Breach encounters such as in Clasped Hand
"The Demon" # Headhunter Leather Belt Two-Implicit Corrupted - Lord of the Grey (Belfry Map), Megaera (Crater Map), The Destroyer's Heart (Lava Lake Map)
"The Doctor" # Headhunter Leather Belt - 68+ SSSS
"The Endless Darkness" # Voidforge Infernal Sword - 81+ The Beachhead, Beachhead (unique harbringer maps), Delve. Harbinger Portals in Kirac's Memory of Phaaryl.
"The Fiend" # Headhunter Leather Belt Corrupted - 68+ Foundry Map • Laboratory Map • Shrine Map • Poorjoy's Asylum
"The Greatest Intentions" # The Saviour Legion Sword Two-Implicit Corrupted - Maven's Invitation: The Feared
"The Shieldbearer" # The Squire Elegant Round Shield - 70+ Citadel Map (t17map)





# uber_loot, sound = 1,
# Sounds:
# 1 = uber_loot
# 10 = great
# good = 3
# skippable = 16
# 12 = league_mechanics_quest
