####################################################################################################
########## Daggers
####################################################################################################
[daggers]
[daggers.glass_shank]
class = "Daggers"
base_type = "Glass Shank"
lvl_required = "1"
dex_required = "9"
int_required = "6"
damage = "6-10"
critical_chance = "6.00%"
aps = "1.5"
dps = "12"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.skinning_knife]
class = "Daggers"
base_type = "Skinning Knife"
lvl_required = "5"
dex_required = "16"
int_required = "11"
damage = "4-17"
critical_chance = "6.00%"
aps = "1.45"
dps = "15.2"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.stiletto]
class = "Daggers"
base_type = "Stiletto"
lvl_required = "15"
dex_required = "30"
int_required = "30"
damage = "7-27"
critical_chance = "6.10%"
aps = "1.5"
dps = "25.5"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.flaying_knife]
class = "Daggers"
base_type = "Flaying Knife"
lvl_required = "30"
dex_required = "64"
int_required = "44"
damage = "11-45"
critical_chance = "6.00%"
aps = "1.4"
dps = "39.2"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.hollowpoint_dagger]
class = "Daggers"
base_type = "Hollowpoint Dagger"
lvl_required = "30"
dex_required = "54"
int_required = "54"
damage = "12-46"
critical_chance = "6.30%"
aps = "1.4"
dps = "40.6"
implicit_mod = "All Damage from Hits with This Weapon can Poison"

[daggers.prong_dagger]
class = "Daggers"
base_type = "Prong Dagger"
lvl_required = "36"
dex_required = "55"
int_required = "77"
damage = "14-54"
critical_chance = "6.20%"
aps = "1.35"
dps = "45.9"
implicit_mod = "4% Chance to Block Attack Damage"

[daggers.poignard]
class = "Daggers"
base_type = "Poignard"
lvl_required = "41"
dex_required = "72"
int_required = "72"
damage = "13-52"
critical_chance = "6.10%"
aps = "1.5"
dps = "48.7"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.pressurised_dagger]
class = "Daggers"
base_type = "Pressurised Dagger"
lvl_required = "50"
dex_required = "86"
int_required = "86"
damage = "18-71"
critical_chance = "6.30%"
aps = "1.4"
dps = "62.3"
implicit_mod = "All Damage from Hits with This Weapon can Poison"

[daggers.trisula]
class = "Daggers"
base_type = "Trisula"
lvl_required = "51"
dex_required = "83"
int_required = "99"
damage = "19-74"
critical_chance = "6.50%"
aps = "1.35"
dps = "62.8"
implicit_mod = "4% Chance to Block Attack Damage"

[daggers.gutting_knife]
class = "Daggers"
base_type = "Gutting Knife"
lvl_required = "56"
dex_required = "113"
int_required = "78"
damage = "19-76"
critical_chance = "6.50%"
aps = "1.4"
dps = "66.5"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.ambusher]
class = "Daggers"
base_type = "Ambusher"
lvl_required = "60"
dex_required = "113"
int_required = "113"
damage = "19-74"
critical_chance = "6.10%"
aps = "1.5"
dps = "69.7"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.sai]
class = "Daggers"
base_type = "Sai"
lvl_required = "70"
dex_required = "121"
int_required = "121"
damage = "22-88"
critical_chance = "6.20%"
aps = "1.35"
dps = "74.2"
implicit_mod = "6% Chance to Block Attack Damage"

[daggers.pneumatic_dagger]
class = "Daggers"
base_type = "Pneumatic Dagger"
lvl_required = "70"
dex_required = "121"
int_required = "121"
damage = "20-79"
critical_chance = "6.30%"
aps = "1.4"
dps = "69.3"
implicit_mod = "All Damage from Hits with This Weapon can Poison"

[daggers.carving_knife]
class = "Rune Daggers"
base_type = "Carving Knife"
lvl_required = "10"
dex_required = "18"
int_required = "26"
damage = "3-26"
critical_chance = "6.30%"
aps = "1.45"
dps = "21"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.boot_knife]
class = "Rune Daggers"
base_type = "Boot Knife"
lvl_required = "20"
dex_required = "31"
int_required = "45"
damage = "8-34"
critical_chance = "6.30%"
aps = "1.45"
dps = "30.4"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.copper_kris]
class = "Rune Daggers"
base_type = "Copper Kris"
lvl_required = "24"
dex_required = "28"
int_required = "60"
damage = "10-41"
critical_chance = "6.50%"
aps = "1.3"
dps = "33.2"
implicit_mod = "50% increased Global Critical Strike Chance"

[daggers.skean]
class = "Rune Daggers"
base_type = "Skean"
lvl_required = "28"
dex_required = "42"
int_required = "60"
damage = "11-43"
critical_chance = "6.30%"
aps = "1.45"
dps = "39.1"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.flickerflame_blade]
class = "Rune Daggers"
base_type = "Flickerflame Blade"
lvl_required = "30"
dex_required = "54"
int_required = "54"
damage = "12-47"
critical_chance = "6.30%"
aps = "1.45"
dps = "42.8"
implicit_mod = "Trigger lvl_required 10 Flame Dash when you use a Socketed Skill"

[daggers.imp_dagger]
class = "Rune Daggers"
base_type = "Imp Dagger"
lvl_required = "32"
dex_required = "36"
int_required = "78"
damage = "15-59"
critical_chance = "6.50%"
aps = "1.2"
dps = "44.4"
implicit_mod = "40% increased Global Critical Strike Chance"

[daggers.butcher_knife]
class = "Rune Daggers"
base_type = "Butcher Knife"
lvl_required = "38"
dex_required = "55"
int_required = "79"
damage = "7-62"
critical_chance = "6.30%"
aps = "1.4"
dps = "48.3"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.boot_blade]
class = "Rune Daggers"
base_type = "Boot Blade"
lvl_required = "44"
dex_required = "63"
int_required = "90"
damage = "15-59"
critical_chance = "6.30%"
aps = "1.4"
dps = "51.8"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.golden_kris]
class = "Rune Daggers"
base_type = "Golden Kris"
lvl_required = "47"
dex_required = "51"
int_required = "110"
damage = "19-75"
critical_chance = "6.50%"
aps = "1.2"
dps = "56.4"
implicit_mod = "50% increased Global Critical Strike Chance"

[daggers.royal_skean]
class = "Rune Daggers"
base_type = "Royal Skean"
lvl_required = "50"
dex_required = "71"
int_required = "102"
damage = "16-64"
critical_chance = "6.30%"
aps = "1.45"
dps = "58"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.flashfire_blade]
class = "Rune Daggers"
base_type = "Flashfire Blade"
lvl_required = "50"
dex_required = "86"
int_required = "86"
damage = "18-73"
critical_chance = "6.30%"
aps = "1.45"
dps = "65.9"
implicit_mod = "Trigger lvl_required 20 Flame Dash when you use a Socketed Skill & 20% increased Cooldown Recovery Rate of Travel Skills"

[daggers.fiend_dagger]
class = "Rune Daggers"
base_type = "Fiend Dagger"
lvl_required = "53"
dex_required = "58"
int_required = "123"
damage = "22-87"
critical_chance = "6.50%"
aps = "1.2"
dps = "65.4"
implicit_mod = "40% increased Global Critical Strike Chance"

[daggers.slaughter_knife]
class = "Rune Daggers"
base_type = "Slaughter Knife"
lvl_required = "58"
dex_required = "81"
int_required = "117"
damage = "10-86"
critical_chance = "6.30%"
aps = "1.4"
dps = "67.2"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.ezomyte_dagger]
class = "Rune Daggers"
base_type = "Ezomyte Dagger"
lvl_required = "62"
dex_required = "95"
int_required = "131"
damage = "20-79"
critical_chance = "6.30%"
aps = "1.4"
dps = "69.3"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.platinum_kris]
class = "Rune Daggers"
base_type = "Platinum Kris"
lvl_required = "64"
dex_required = "76"
int_required = "149"
damage = "24-95"
critical_chance = "6.50%"
aps = "1.2"
dps = "71.4"
implicit_mod = "50% increased Global Critical Strike Chance"

[daggers.imperial_skean]
class = "Rune Daggers"
base_type = "Imperial Skean"
lvl_required = "66"
dex_required = "95"
int_required = "131"
damage = "18-73"
critical_chance = "6.30%"
aps = "1.5"
dps = "68.2"
implicit_mod = "30% increased Global Critical Strike Chance"

[daggers.demon_dagger]
class = "Rune Daggers"
base_type = "Demon Dagger"
lvl_required = "68"
dex_required = "76"
int_required = "149"
damage = "24-97"
critical_chance = "6.50%"
aps = "1.2"
dps = "72.6"
implicit_mod = "40% increased Global Critical Strike Chance"

[daggers.infernal_blade]
class = "Rune Daggers"
base_type = "Infernal Blade"
lvl_required = "70"
dex_required = "121"
int_required = "121"
damage = "21-85"
critical_chance = "6.30%"
aps = "1.45"
dps = "76.8"
implicit_mod = "Trigger lvl_required 30 Flame Dash when you use a Socketed Skill & 40% increased Cooldown Recovery Rate of Travel Skills"
