[swords.corroded_blade]
class = "Two Hand Swords"
base_type = "Corroded Blade"
lvl_required = "1"
str_required = "11"
dex_required = "11"
damage = "8-16"
critical_chance = "5.00%"
aps = "1.45"
dps = "17.4"
implicit_mod = "40% increased Global Accuracy Rating"

[swords.longsword]
class = "Two Hand Swords"
base_type = "Longsword"
lvl_required = "8"
str_required = "20"
dex_required = "17"
damage = "11-26"
critical_chance = "5.00%"
aps = "1.4"
dps = "25.9"
implicit_mod = "+60 to Accuracy Rating"

[swords.bastard_sword]
class = "Two Hand Swords"
base_type = "Bastard Sword"
lvl_required = "12"
str_required = "21"
dex_required = "30"
damage = "17-29"
critical_chance = "5.00%"
aps = "1.45"
dps = "33.3"
implicit_mod = "60% increased Global Accuracy Rating"

[swords.two-handed_sword]
class = "Two Hand Swords"
base_type = "Two-Handed Sword"
lvl_required = "17"
str_required = "33"
dex_required = "33"
damage = "20-38"
critical_chance = "5.00%"
aps = "1.4"
dps = "40.6"
implicit_mod = "+120 to Accuracy Rating"

[swords.etched_greatsword]
class = "Two Hand Swords"
base_type = "Etched Greatsword"
lvl_required = "22"
str_required = "45"
dex_required = "38"
damage = "23-48"
critical_chance = "5.00%"
aps = "1.4"
dps = "49.7"
implicit_mod = "60% increased Global Accuracy Rating"

[swords.ornate_sword]
class = "Two Hand Swords"
base_type = "Ornate Sword"
lvl_required = "27"
str_required = "45"
dex_required = "54"
damage = "30-50"
critical_chance = "5.00%"
aps = "1.4"
dps = "56"
implicit_mod = "+185 to Accuracy Rating"

[swords.rebuking_blade]
class = "Two Hand Swords"
base_type = "Rebuking Blade"
lvl_required = "30"
str_required = "54"
dex_required = "54"
damage = "30-56"
critical_chance = "6.50%"
aps = "1.4"
dps = "60.2"
implicit_mod = "Attack Critical Strikes ignore Enemy Monster Elemental Resistances"

[swords.spectral_sword]
class = "Two Hand Swords"
base_type = "Spectral Sword"
lvl_required = "32"
str_required = "57"
dex_required = "57"
damage = "31-65"
critical_chance = "5.00%"
aps = "1.35"
dps = "64.8"
implicit_mod = "45% increased Global Accuracy Rating"

[swords.curved_blade]
class = "Two Hand Swords"
base_type = "Curved Blade"
lvl_required = "35"
str_required = "62"
dex_required = "73"
damage = "41-68"
critical_chance = "6.00%"
aps = "1.35"
dps = "73.5"
implicit_mod = "+40% to Global Critical Strike Multiplier"

[swords.butcher_sword]
class = "Two Hand Swords"
base_type = "Butcher Sword"
lvl_required = "36"
str_required = "69"
dex_required = "58"
damage = "34-79"
critical_chance = "5.00%"
aps = "1.3"
dps = "73.5"
implicit_mod = "+250 to Accuracy Rating"

[swords.footman_sword]
class = "Two Hand Swords"
base_type = "Footman Sword"
lvl_required = "40"
str_required = "57"
dex_required = "83"
damage = "39-65"
critical_chance = "5.00%"
aps = "1.45"
dps = "75.4"
implicit_mod = "60% increased Global Accuracy Rating"

[swords.highland_blade]
class = "Two Hand Swords"
base_type = "Highland Blade"
lvl_required = "44"
str_required = "77"
dex_required = "77"
damage = "45-84"
critical_chance = "5.00%"
aps = "1.35"
dps = "87"
implicit_mod = "+305 to Accuracy Rating"

[swords.engraved_greatsword]
class = "Two Hand Swords"
base_type = "Engraved Greatsword"
lvl_required = "48"
str_required = "91"
dex_required = "76"
damage = "49-102"
critical_chance = "5.00%"
aps = "1.3"
dps = "98.2"
implicit_mod = "60% increased Global Accuracy Rating"

[swords.blasting_blade]
class = "Two Hand Swords"
base_type = "Blasting Blade"
lvl_required = "50"
str_required = "86"
dex_required = "86"
damage = "47-87"
critical_chance = "6.50%"
aps = "1.4"
dps = "93.8"
implicit_mod = "Attack Critical Strikes ignore Enemy Monster Elemental Resistances"

[swords.tiger_sword]
class = "Two Hand Swords"
base_type = "Tiger Sword"
lvl_required = "51"
str_required = "80"
dex_required = "96"
damage = "54-89"
critical_chance = "5.00%"
aps = "1.4"
dps = "100.1"
implicit_mod = "+360 to Accuracy Rating"

[swords.wraith_sword]
class = "Two Hand Swords"
base_type = "Wraith Sword"
lvl_required = "54"
str_required = "93"
dex_required = "93"
damage = "52-109"
critical_chance = "5.00%"
aps = "1.35"
dps = "108.6"
implicit_mod = "45% increased Global Accuracy Rating"

[swords.lithe_blade]
class = "Two Hand Swords"
base_type = "Lithe Blade"
lvl_required = "56"
str_required = "96"
dex_required = "113"
damage = "63-104"
critical_chance = "6.00%"
aps = "1.35"
dps = "112.7"
implicit_mod = "+40% to Global Critical Strike Multiplier"

[swords.headmans_sword]
class = "Two Hand Swords"
base_type = "Headman's Sword"
lvl_required = "57"
str_required = "106"
dex_required = "89"
damage = "55-128"
critical_chance = "5.00%"
aps = "1.3"
dps = "119"
implicit_mod = "+400 to Accuracy Rating"

[swords.reaver_sword]
class = "Two Hand Swords"
base_type = "Reaver Sword"
lvl_required = "59"
str_required = "82"
dex_required = "119"
damage = "62-104"
critical_chance = "5.00%"
aps = "1.5"
dps = "124.4"
implicit_mod = "60% increased Global Accuracy Rating"

[swords.ezomyte_blade]
class = "Two Hand Swords"
base_type = "Ezomyte Blade"
lvl_required = "61"
str_required = "113"
dex_required = "113"
damage = "62-115"
critical_chance = "6.50%"
aps = "1.4"
dps = "123.9"
implicit_mod = "+25% to Global Critical Strike Multiplier"

[swords.vaal_greatsword]
class = "Two Hand Swords"
base_type = "Vaal Greatsword"
lvl_required = "63"
str_required = "122"
dex_required = "104"
damage = "68-142"
critical_chance = "5.00%"
aps = "1.3"
dps = "136.5"
implicit_mod = "+470 to Accuracy Rating"

[swords.lion_sword]
class = "Two Hand Swords"
base_type = "Lion Sword"
lvl_required = "65"
str_required = "104"
dex_required = "122"
damage = "69-115"
critical_chance = "5.00%"
aps = "1.45"
dps = "133.3"
implicit_mod = "+50 to Strength and Dexterity"

[swords.infernal_sword]
class = "Two Hand Swords"
base_type = "Infernal Sword"
lvl_required = "67"
str_required = "113"
dex_required = "113"
damage = "62-129"
critical_chance = "5.00%"
aps = "1.35"
dps = "128.9"
implicit_mod = "30% increased Elemental Damage with Attack Skills"

[swords.exquisite_blade]
class = "Two Hand Swords"
base_type = "Exquisite Blade"
lvl_required = "70"
str_required = "119"
dex_required = "131"
damage = "67-112"
critical_chance = "5.70%"
aps = "1.35"
dps = "120.8"
implicit_mod = "+50% to Global Critical Strike Multiplier"

[swords.banishing_blade]
class = "Two Hand Swords"
base_type = "Banishing Blade"
lvl_required = "70"
str_required = "130"
dex_required = "130"
damage = "55-102"
critical_chance = "6.50%"
aps = "1.4"
dps = "109.9"
implicit_mod = "Attack Critical Strikes ignore Enemy Monster Elemental Resistances"

