
[[favorite]]
name = "Azyran's Reward"
reward = "Prismatic Jewel Corrupted (can drop watcher)"
drop_level = 68
info = "Laboratory Map • Relic Chambers Map • Stagnation Map"

[[favorite]]
name = "Chasing Risk"
reward = "Synthesis Item (can drop bottled faith)"
drop_level = 81
info = "Drops from the Vaal Omnitect in areas of level 79 or greater."

[[favorite]]
name = "Fateful Meeting"
reward = "League-Specific Item Double-Influenced Item Item Level: 97 Two-Implicit Corrupted"
drop_level = 80
info = "Drops from Vaal Flesh Merchant, a monster which appears in Alva's temporal incursions if you have the atlas passive skill Vaal Oligarchs allocated."

[[favorite]]
name = "Peaceful Moments"
reward = "Timeless Jewel"
drop_level = 68
info = "Courtyard Map • Gardens Map • Orchard Map • Terrace Map"

[[favorite]]
name = "The Eternal War"
reward = "Timeless Jewel Two-Implicit Corrupted"
drop_level = 68
info = "Al-Hezmin The Hunter, Baran The Crusader, Drox The Warlord, Veritania The Redeemer"


[[favorite]]
name = "Pride of the First Ones"
reward = "Farrul's Fur Triumphant Lamellar"
drop_level = 80
info = "Barrows Map • Grotto Map • Lair Map • Caer Blaidd, Wolfpack's Den"


[[favorite]]
name = "The Garish Power"
reward = "unique jewel"
drop_level = 23
info = "The Chamber of Sins Level 1 (Act 7) • The Chamber of Sins Level 2 (Act 7) • Overgrown Ruin Map • Overgrown Shrine Map"

[[good]]
name = "The Eye of the Dragon"
reward = "jewel Corrupted (not most expensive, but ok)"
drop_level = 23
info = "The Boiling Lake • Forge of the Phoenix Map • Sulphur Vents Map"

[[hide]]
name = "A Familiar Call"
reward = "blue jewellery of farrul shaper + hunter item"
drop_level = 0
info = "todo"

[[good]]
name = "Arrogance of the Vaal"
reward = "unique item Two-Implicit Corrupted"
drop_level = 54
info = "Ancient City Map • Sunken City Map • Vaal Pyramid Map"

[[good]]
name = "Boon of the First Ones"
reward = "Bestiary Item"
drop_level = 72
info = "Pit of the Chimera Map"



[[good]]
name = "Council of Cats"
reward = "farrul item (often expensive)"
drop_level = 80
info = "Al-Hezmin The Hunter"


[[hide]]
name = "Hunter's Reward"
reward = "The Taming Prismatic Ring"
drop_level = 0
info = "TODO"

[[hide]]
name = "Judging Voices"
reward = "Forbidden Shako Great Crown"
drop_level = 0
info = "TODO"

[[hide]]
name = "Remembrance"
reward = "Precursor's Emblem (ring) Corrupted"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Aspirant"
reward = "blue enchanged and influenced item"
drop_level = 0
info = "Harvest boss"

[[hide]]
name = "The Awakened"
reward = "yellow double influenced jewelery"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Celestial Stone"
reward = "opal ring shaper"
drop_level = 0
info = "TODO"

[[hide]]
name = "The Damned"
reward = "Soul Ripper Quartz Flask"
drop_level = 0
info = "TODO"

[[favorite]]
name = "The Dreamer"
reward = "Chayula Item"
drop_level = 68
info = "Agent of the Void"

[[hide]]
name = "The Enthusiasts"
reward = "Victario's Influence Lacquered Garb Two-Implicit Corrupted"
drop_level = 0
info = "TODO"

[[favorite]]
name = "The Hunger"
reward = "Taste of Hate Sapphire Flask"
drop_level = 38
info = "The Belly of the Beast Level 1 • The Belly of the Beast Level 2 • The Harvest (area) • The Belly of the Beast (Act 9) • The Rotting Core • Abomination Map • Carcass Map • Core Map • Malformation Map • Phantasmagoria Map"

[[hide]]
name = "The Leviathan"
reward = "Maven Item Two-Implicit Corrupted - 81+ Maelström of Chaos Atoll Map (rf boots)"
drop_level = 0
info = "TODO"

[[favorite]]
name = "The Risk"
reward = "Ventor's Gamble gold ring"
drop_level = 49
info = "The Risk can drop from the following loot containers: Diviner's Strongbox Izaro's Treasure in the Endgame Labyrinth"

[[good]]
name = "The Undaunted"
reward = "nemesis item Corrupted (can drop headhunter)"
drop_level = 23
info = "Courthouse Map • Precinct Map • Whakawairua Tuahu"

[[good]]
name = "The Valkyrie"
reward = "nemesis item (can drop headhunter)"
drop_level = 23
info = "Drops from female Rogue Exiles."

[[good]]
name = "The Void"
reward = "random card"
drop_level = 23
info = "Abomination Map • Citadel Map • Fortress Map • Sanctuary Map • Ziggurat Map"


[[favorite]]
name = "The Wretched"
reward = "belt (can drop mageblood and headhunter)"
drop_level = 68
info = "Bone Crypt Map • Citadel Map • Cursed Crypt Map • The Coward's Trial • Necropolis Map • Acton's Nightmare • Ziggurat Map"



[[hide]]
name = "Ambitious Obsession"
reward = "skittering delerium orb"
drop_level = 0
info = "TODO"

[[good]]
name = "Checkmate"
reward = "76x simulacrum splinter"
drop_level = 68
info = "Academy Map • Museum Map • Scriptorium Map"


[[favorite]]
name = "The Obscured"
reward = "Breachstone"
drop_level = 68
info = "The Obscured can drop from Abyss monsters, including from Abyss nodes in Delve."

[[hide]]
name = "Vinia's Token"
reward = "10x orb of regret"
drop_level = 0
info = "todo"


[[favorite]]
name = "Haunting Shadows"
reward = "Metamorph Item"
drop_level = 68
info = "The Twilight Temple Unique Map"
